/*
 * iosc_gl.h — ANGLE (GLES→Metal) GPU compositor for iosc.
 *
 * iosc holds one EGL context whose render target is the OUTPUT IOSurface (the
 * surface the Xios app presents via Metal). Each committed client buffer is drawn
 * as a textured quad into that output on the GPU. For a client that handed over an
 * IOSurface (the ANGLE-Metal GPU path), the surface is adopted directly as a
 * GL/Metal texture (EGL_ANGLE_iosurface_client_buffer) and sampled — NO CPU copy,
 * the whole per-frame path stays on the GPU. wl_shm buffers are CPU pixels, so they
 * cost one glTexImage2D upload. All EGL/GLES code is isolated here so iosc.c stays
 * free of GL headers. Production callers fail closed if initialization fails;
 * iosc's incomplete CPU compositor is an explicit diagnostic-only mode.
 */
#ifndef IOSC_GL_H
#define IOSC_GL_H

#include <stddef.h>
#include <stdint.h>

/* Set up the EGL context + output framebuffer bound to `output_iosurface`
 * (opaque IOSurfaceRef) at w x h. 0 on success; nonzero means GPU init failed. */
int  iosc_gl_init(void *output_iosurface, int w, int h);

/* True once iosc_gl_init() has succeeded. */
int  iosc_gl_ok(void);

/* Rebind the render target to a NEW output IOSurface at w x h (device rotation:
 * iosc reallocated the output via xios_surface_resize). The EGL display/context,
 * shader program, and the client-surface texture cache all survive; only the
 * output pbuffer/texture/FBO are torn down and rebuilt. 0 on success; on failure
 * the GPU path is marked unavailable. Production iosc terminates rather than
 * silently changing rendering architecture. */
int  iosc_gl_resize(void *output_iosurface, int w, int h);

/* Rebind the current EGL render target/FBO to an IOSurface without recreating the
 * context, shader program, or client texture caches. This is the native-iPadOS
 * per-window hook: callers can bind a window canvas, draw, end, then bind another
 * canvas. It is also the implementation behind iosc_gl_resize(). */
int  iosc_gl_bind_target(void *iosurface, int w, int h);

/* Begin a frame: bind the output FBO and clear to black. */
void iosc_gl_begin(void);

/* Begin a partial frame: clear/draw only the output-pixel damage rect. Coordinates
 * are in iosc's top-left output space; the GL backend maps them to its mirrored FBO
 * convention. Passing an empty/full rect is equivalent to iosc_gl_begin(). */
void iosc_gl_begin_damage(int x, int y, int w, int h);

/* Change the current damage scissor without clearing. Used inside a partial frame
 * to clip a single surface to the rect pieces still visible after occlusion. */
void iosc_gl_set_damage(int x, int y, int w, int h);

/* Draw a client IOSurface (opaque IOSurfaceRef) of source size sw x sh as a quad
 * at output-pixel dest rect (dx,dy,dw,dh). Zero-copy: the IOSurface is sampled
 * directly as a GL/Metal texture (the texture is sized to the surface, sw x sh). */
void iosc_gl_draw_iosurface(void *client_iosurface, int sw, int sh,
                            int sx, int sy, int src_w, int src_h,
                            int dx, int dy, int dw, int dh, int flip_v);

/* Draw a wl_shm BGRA buffer as a quad at the dest rect. `key` (a stable
 * per-surface pointer) caches one GL texture per surface: the buffer is uploaded
 * only when `dirty` (or the size changed), so an unchanged surface re-drawn on a
 * cursor-move repaint costs no upload. When dirty rectangles are supplied, only
 * those buffer-regions are uploaded. Pass key=NULL for transient/uncached buffers
 * (single-pixel, the procedural cursor); those always upload. */
void iosc_gl_draw_shm(void *key, int dirty, const void *data, int sw, int sh, int stride,
                      int dirty_rect_count, const int *dirty_rects,
                      int sx, int sy, int src_w, int src_h,
                      int dx, int dy, int dw, int dh);

/* Drop the cached texture for a surface `key` that is going away (its address may
 * be reused by a later surface). Safe to call for keys that were never cached. */
void iosc_gl_forget_shm(void *key);

/* End the frame. Production requires a cross-process MTLSharedEvent signal so
 * the producer CPU does not wait. IOSC_ALLOW_CPU_SYNC_DIAGNOSTIC=1 retains a
 * correctness-only EGL-fence/glFinish barrier for narrow bring-up. */
void iosc_gl_end(void);

/* Fence generated by the most recent iosc_gl_end(). The token identifies a
 * persistent MTLSharedEventHandle published once through the package broker;
 * `value` identifies this frame. Returns 1 when the Xios app must encode a GPU
 * wait before sampling; 0 is fatal in production (or means the explicit
 * CPU-sync diagnostic mode completed its barrier). */
int iosc_gl_present_fence(const void **token, size_t *token_size,
                          uint64_t *value);

/* Import-side counterpart used by IOSurface-backed Wayland clients: enqueue a
 * GPU wait before sampling a buffer produced on another Metal command queue. */
int iosc_gl_wait_shared_event(void *event, uint64_t value);

/* Read one composited output pixel (BGRA) at top-left coord (x,y) — validation
 * (proves a given window's content landed at its placement). Call after iosc_gl_end. */
uint32_t iosc_gl_read_at(int x, int y);

/* Read the composited output center pixel (BGRA) — validation only (IOSC_DEBUG). */
uint32_t iosc_gl_read_center(void);

/* Wrap a composite in premultiplied-alpha blending so the buffer's real alpha is
 * honored (source-over) instead of drawing opaque. Used for the cursor and DnD
 * icon (transparent around the artwork) and for layer-shell surfaces (the shell's
 * translucent panel/overview chrome). Call begin before the draw and end after;
 * windows draw between frames with blending off and alpha forced opaque. */
void iosc_gl_begin_blend(void);
void iosc_gl_end_blend(void);

/* Drop the cached pbuffer/texture for a client IOSurface that is going away. */
void iosc_gl_forget_iosurface(void *client_iosurface);

#endif /* IOSC_GL_H */
