ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# attica.mk — kf6-attica for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Workspace pulls this through KNewStuff. It is Qt Core+Network only and
# does not need a first-light feature cut.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += attica
ATTICA_VERSION = $(KF6_VERSION)
DEB_ATTICA_V ?= $(ATTICA_VERSION)+ios1

attica-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,attica))
	$(call EXTRACT_TAR,attica-$(KF6_VERSION).tar.xz,attica-$(KF6_VERSION),attica)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/attica/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/attica/.build_complete),)
attica:
	@echo "Using previously built attica."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
attica: attica-setup
	mkdir -p $(BUILD_WORK)/attica/build
	cd $(BUILD_WORK)/attica/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/attica/build
	+DESTDIR="$(BUILD_STAGE)/attica" ninja -C $(BUILD_WORK)/attica/build install
	$(call AFTER_BUILD,copy)
endif

attica-package: attica-stage
	rm -rf $(BUILD_DIST)/kf6-attica $(BUILD_DIST)/kf6-attica-dev
	$(call KF6_COPY_RUNTIME,attica,kf6-attica)
	$(call KF6_COPY_DEV,attica,kf6-attica)
	$(call SIGN,kf6-attica,general.xml)
	$(call SIGN,kf6-attica-dev,general.xml)
	$(call PACK,kf6-attica,DEB_ATTICA_V)
	$(call PACK,kf6-attica-dev,DEB_ATTICA_V)
	rm -rf $(BUILD_DIST)/kf6-attica $(BUILD_DIST)/kf6-attica-dev

.PHONY: attica attica-package
