ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# breeze-icons.mk — kf6-breeze-icons for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Data-only (icon files + cmake config in one deb, no SIGN). KIconThemes
# REQUIREs it at build on non-Android, so it sits in wave 1, not in theming
# polish. BINARY_ICONS_RESOURCE=OFF skips the icons.rcc bake; plain files are
# friendlier to the icon repack pipeline anyway.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += breeze-icons
BREEZEICONS_VERSION = $(KF6_VERSION)
DEB_BREEZEICONS_V ?= $(BREEZEICONS_VERSION)+ios1

breeze-icons-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,breeze-icons))
	$(call EXTRACT_TAR,breeze-icons-$(KF6_VERSION).tar.xz,breeze-icons-$(KF6_VERSION),breeze-icons)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/breeze-icons/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/breeze-icons/.build_complete),)
breeze-icons:
	@echo "Using previously built breeze-icons."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
breeze-icons: breeze-icons-setup
	mkdir -p $(BUILD_WORK)/breeze-icons/build
	cd $(BUILD_WORK)/breeze-icons/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DBINARY_ICONS_RESOURCE=OFF
	+ninja -C $(BUILD_WORK)/breeze-icons/build
	+DESTDIR="$(BUILD_STAGE)/breeze-icons" ninja -C $(BUILD_WORK)/breeze-icons/build install
	$(call AFTER_BUILD,copy)
endif

breeze-icons-package: breeze-icons-stage
	rm -rf $(BUILD_DIST)/kf6-breeze-icons
	$(call KF6_COPY_ALL,breeze-icons,kf6-breeze-icons)
	$(call PACK,kf6-breeze-icons,DEB_BREEZEICONS_V)
	rm -rf $(BUILD_DIST)/kf6-breeze-icons

.PHONY: breeze-icons breeze-icons-package
