ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# extra-cmake-modules.mk — extra-cmake-modules for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# ECM is cmake scripts only (arch-independent): one deb, no dev split, no
# SIGN. The same staged tree serves the cross builds (CMAKE_FIND_ROOT_PATH)
# and, via CMAKE_PREFIX_PATH, the stage-1 host tooling builds in build-kf6.sh.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += extra-cmake-modules
EXTRACMAKEMODULES_VERSION = $(KF6_VERSION)
DEB_EXTRACMAKEMODULES_V ?= $(EXTRACMAKEMODULES_VERSION)

extra-cmake-modules-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,extra-cmake-modules))
	$(call EXTRACT_TAR,extra-cmake-modules-$(KF6_VERSION).tar.xz,extra-cmake-modules-$(KF6_VERSION),extra-cmake-modules)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/extra-cmake-modules/.build_complete),)
extra-cmake-modules:
	@echo "Using previously built extra-cmake-modules."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
extra-cmake-modules: extra-cmake-modules-setup
	mkdir -p $(BUILD_WORK)/extra-cmake-modules/build
	cd $(BUILD_WORK)/extra-cmake-modules/build && cmake .. \
		-G Ninja \
		$(DEFAULT_CMAKE_FLAGS) \
		-DBUILD_TESTING=OFF
	+ninja -C $(BUILD_WORK)/extra-cmake-modules/build
	+DESTDIR="$(BUILD_STAGE)/extra-cmake-modules" ninja -C $(BUILD_WORK)/extra-cmake-modules/build install
	$(call AFTER_BUILD,copy)
endif

extra-cmake-modules-package: extra-cmake-modules-stage
	rm -rf $(BUILD_DIST)/extra-cmake-modules
	$(call KF6_COPY_ALL,extra-cmake-modules,extra-cmake-modules)
	$(call PACK,extra-cmake-modules,DEB_EXTRACMAKEMODULES_V)
	rm -rf $(BUILD_DIST)/extra-cmake-modules

.PHONY: extra-cmake-modules extra-cmake-modules-package
