ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# bzip2/xz/zstd backends disabled: zlib comes from the SDK, but the compression side-deps
# would add Depends we'd have to name blind (Procursus libsqlite3-1 naming lesson).
# KPackage/KIconThemes only need zip/tar.gz. Use WITH_*=OFF, not
# CMAKE_DISABLE_FIND_PACKAGE: WITH_*=ON marks each backend REQUIRED (bzip2/lzma via
# feature_summary, zstd via pkg_check_modules REQUIRED), so disabling find-package alone
# still fatals; WITH_*=OFF demotes them to RECOMMENDED.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += karchive
KARCHIVE_VERSION = $(KF6_VERSION)
DEB_KARCHIVE_V ?= $(KARCHIVE_VERSION)+ios1

karchive-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,karchive))
	$(call EXTRACT_TAR,karchive-$(KF6_VERSION).tar.xz,karchive-$(KF6_VERSION),karchive)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/karchive/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/karchive/.build_complete),)
karchive:
	@echo "Using previously built karchive."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
karchive: karchive-setup
	mkdir -p $(BUILD_WORK)/karchive/build
	cd $(BUILD_WORK)/karchive/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DWITH_BZIP2=OFF \
		-DWITH_LIBLZMA=OFF \
		-DWITH_LIBZSTD=OFF
	+ninja -C $(BUILD_WORK)/karchive/build
	+DESTDIR="$(BUILD_STAGE)/karchive" ninja -C $(BUILD_WORK)/karchive/build install
	$(call AFTER_BUILD,copy)
endif

karchive-package: karchive-stage
	rm -rf $(BUILD_DIST)/kf6-archive $(BUILD_DIST)/kf6-archive-dev
	$(call KF6_COPY_RUNTIME,karchive,kf6-archive)
	$(call KF6_COPY_DEV,karchive,kf6-archive)
	$(call SIGN,kf6-archive,general.xml)
	$(call SIGN,kf6-archive-dev,general.xml)
	$(call PACK,kf6-archive,DEB_KARCHIVE_V)
	$(call PACK,kf6-archive-dev,DEB_KARCHIVE_V)
	rm -rf $(BUILD_DIST)/kf6-archive $(BUILD_DIST)/kf6-archive-dev

.PHONY: karchive karchive-package
