ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kauth.mk — kf6-auth for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# FAKE backend on purpose: the real one wants polkit-qt6-1 (a lib we have not
# built; only plain polkit exists) and the jailbreak runtime has no privilege
# boundary that KAuth could meaningfully broker anyway. Revisit if a Plasma
# KCM genuinely needs privileged apply.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kauth
KAUTH_VERSION = $(KF6_VERSION)
DEB_KAUTH_V ?= $(KAUTH_VERSION)

kauth-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kauth))
	$(call EXTRACT_TAR,kauth-$(KF6_VERSION).tar.xz,kauth-$(KF6_VERSION),kauth)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kauth/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kauth/.build_complete),)
kauth:
	@echo "Using previously built kauth."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kauth: kauth-setup
	mkdir -p $(BUILD_WORK)/kauth/build
	cd $(BUILD_WORK)/kauth/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DKAUTH_BACKEND_NAME=FAKE \
		-DKAUTH_HELPER_BACKEND_NAME=FAKE
	+ninja -C $(BUILD_WORK)/kauth/build
	+DESTDIR="$(BUILD_STAGE)/kauth" ninja -C $(BUILD_WORK)/kauth/build install
	$(call AFTER_BUILD,copy)
endif

kauth-package: kauth-stage
	rm -rf $(BUILD_DIST)/kf6-auth $(BUILD_DIST)/kf6-auth-dev
	$(call KF6_COPY_RUNTIME,kauth,kf6-auth)
	$(call KF6_COPY_DEV,kauth,kf6-auth)
	$(call SIGN,kf6-auth,general.xml)
	$(call SIGN,kf6-auth-dev,general.xml)
	$(call PACK,kf6-auth,DEB_KAUTH_V)
	$(call PACK,kf6-auth-dev,DEB_KAUTH_V)
	rm -rf $(BUILD_DIST)/kf6-auth $(BUILD_DIST)/kf6-auth-dev

.PHONY: kauth kauth-package
