ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kbookmarks.mk — kf6-bookmarks for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Only in the subset as a hard KIO dep.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kbookmarks
KBOOKMARKS_VERSION = $(KF6_VERSION)
DEB_KBOOKMARKS_V ?= $(KBOOKMARKS_VERSION)

kbookmarks-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kbookmarks))
	$(call EXTRACT_TAR,kbookmarks-$(KF6_VERSION).tar.xz,kbookmarks-$(KF6_VERSION),kbookmarks)
	$(call QT6_WRITE_IOSEXEC_FIXUP)

ifneq ($(wildcard $(BUILD_WORK)/kbookmarks/.build_complete),)
kbookmarks:
	@echo "Using previously built kbookmarks."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kbookmarks: kbookmarks-setup
	mkdir -p $(BUILD_WORK)/kbookmarks/build
	cd $(BUILD_WORK)/kbookmarks/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kbookmarks/build
	+DESTDIR="$(BUILD_STAGE)/kbookmarks" ninja -C $(BUILD_WORK)/kbookmarks/build install
	$(call AFTER_BUILD,copy)
endif

kbookmarks-package: kbookmarks-stage
	rm -rf $(BUILD_DIST)/kf6-bookmarks $(BUILD_DIST)/kf6-bookmarks-dev
	$(call KF6_COPY_RUNTIME,kbookmarks,kf6-bookmarks)
	$(call KF6_COPY_DEV,kbookmarks,kf6-bookmarks)
	$(call SIGN,kf6-bookmarks,general.xml)
	$(call SIGN,kf6-bookmarks-dev,general.xml)
	$(call PACK,kf6-bookmarks,DEB_KBOOKMARKS_V)
	$(call PACK,kf6-bookmarks-dev,DEB_KBOOKMARKS_V)
	rm -rf $(BUILD_DIST)/kf6-bookmarks $(BUILD_DIST)/kf6-bookmarks-dev

.PHONY: kbookmarks kbookmarks-package
