ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kcmutils.mk — kf6-kcmutils for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Top of the widget-tier chain: libplasma REQUIREs KCMUtils, KCMUtils REQUIREs
# KXmlGui + KIO, and that chain (not kwin) is what drags ktextwidgets/sonnet/
# kbookmarks into the subset. Uses QtQuickWidgets from qt6-declarative.
# Its Config.cmake assumes host-built tooling targets while cross-compiling;
# the sed lets consumers fall back to the installed local tooling targets
# when no host KCMUtils tooling build exists.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kcmutils
KCMUTILS_VERSION = $(KF6_VERSION)
DEB_KCMUTILS_V ?= $(KCMUTILS_VERSION)+ios1

kcmutils-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kcmutils))
	$(call EXTRACT_TAR,kcmutils-$(KF6_VERSION).tar.xz,kcmutils-$(KF6_VERSION),kcmutils)
	sed -i 's|PATHS $${KF6_HOST_TOOLING} $${CMAKE_CURRENT_LIST_DIR}|PATHS $${KF6_HOST_TOOLING} $${CMAKE_CURRENT_LIST_DIR}/.. $${CMAKE_CURRENT_LIST_DIR}|' $(BUILD_WORK)/kcmutils/KF6KCMUtilsConfig.cmake.in
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kcmutils/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kcmutils/.build_complete),)
kcmutils:
	@echo "Using previously built kcmutils."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kcmutils: kcmutils-setup
	mkdir -p $(BUILD_WORK)/kcmutils/build
	cd $(BUILD_WORK)/kcmutils/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kcmutils/build
	+DESTDIR="$(BUILD_STAGE)/kcmutils" ninja -C $(BUILD_WORK)/kcmutils/build install
	$(call AFTER_BUILD,copy)
endif

kcmutils-package: kcmutils-stage
	rm -rf $(BUILD_DIST)/kf6-kcmutils $(BUILD_DIST)/kf6-kcmutils-dev
	$(call KF6_COPY_RUNTIME,kcmutils,kf6-kcmutils)
	$(call KF6_COPY_DEV,kcmutils,kf6-kcmutils)
	$(call SIGN,kf6-kcmutils,general.xml)
	$(call SIGN,kf6-kcmutils-dev,general.xml)
	$(call PACK,kf6-kcmutils,DEB_KCMUTILS_V)
	$(call PACK,kf6-kcmutils-dev,DEB_KCMUTILS_V)
	rm -rf $(BUILD_DIST)/kf6-kcmutils $(BUILD_DIST)/kf6-kcmutils-dev

.PHONY: kcmutils kcmutils-package
