ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kcodecs.mk — kf6-codecs for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Needs gperf on the build host (build-kf6.sh apt-installs it).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kcodecs
KCODECS_VERSION = $(KF6_VERSION)
DEB_KCODECS_V ?= $(KCODECS_VERSION)

kcodecs-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kcodecs))
	$(call EXTRACT_TAR,kcodecs-$(KF6_VERSION).tar.xz,kcodecs-$(KF6_VERSION),kcodecs)
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kcodecs/.build_complete),)
kcodecs:
	@echo "Using previously built kcodecs."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kcodecs: kcodecs-setup
	mkdir -p $(BUILD_WORK)/kcodecs/build
	cd $(BUILD_WORK)/kcodecs/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kcodecs/build
	+DESTDIR="$(BUILD_STAGE)/kcodecs" ninja -C $(BUILD_WORK)/kcodecs/build install
	$(call AFTER_BUILD,copy)
endif

kcodecs-package: kcodecs-stage
	rm -rf $(BUILD_DIST)/kf6-codecs $(BUILD_DIST)/kf6-codecs-dev
	$(call KF6_COPY_RUNTIME,kcodecs,kf6-codecs)
	$(call KF6_COPY_DEV,kcodecs,kf6-codecs)
	$(call SIGN,kf6-codecs,general.xml)
	$(call SIGN,kf6-codecs-dev,general.xml)
	$(call PACK,kf6-codecs,DEB_KCODECS_V)
	$(call PACK,kf6-codecs-dev,DEB_KCODECS_V)
	rm -rf $(BUILD_DIST)/kf6-codecs $(BUILD_DIST)/kf6-codecs-dev

.PHONY: kcodecs kcodecs-package
