ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kcolorscheme.mk — kf6-colorscheme for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kcolorscheme
KCOLORSCHEME_VERSION = $(KF6_VERSION)
DEB_KCOLORSCHEME_V ?= $(KCOLORSCHEME_VERSION)

kcolorscheme-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kcolorscheme))
	$(call EXTRACT_TAR,kcolorscheme-$(KF6_VERSION).tar.xz,kcolorscheme-$(KF6_VERSION),kcolorscheme)
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kcolorscheme/.build_complete),)
kcolorscheme:
	@echo "Using previously built kcolorscheme."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kcolorscheme: kcolorscheme-setup
	mkdir -p $(BUILD_WORK)/kcolorscheme/build
	cd $(BUILD_WORK)/kcolorscheme/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kcolorscheme/build
	+DESTDIR="$(BUILD_STAGE)/kcolorscheme" ninja -C $(BUILD_WORK)/kcolorscheme/build install
	$(call AFTER_BUILD,copy)
endif

kcolorscheme-package: kcolorscheme-stage
	rm -rf $(BUILD_DIST)/kf6-colorscheme $(BUILD_DIST)/kf6-colorscheme-dev
	$(call KF6_COPY_RUNTIME,kcolorscheme,kf6-colorscheme)
	$(call KF6_COPY_DEV,kcolorscheme,kf6-colorscheme)
	$(call SIGN,kf6-colorscheme,general.xml)
	$(call SIGN,kf6-colorscheme-dev,general.xml)
	$(call PACK,kf6-colorscheme,DEB_KCOLORSCHEME_V)
	$(call PACK,kf6-colorscheme-dev,DEB_KCOLORSCHEME_V)
	rm -rf $(BUILD_DIST)/kf6-colorscheme $(BUILD_DIST)/kf6-colorscheme-dev

.PHONY: kcolorscheme kcolorscheme-package
