ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kcompletion.mk — kf6-completion for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kcompletion
KCOMPLETION_VERSION = $(KF6_VERSION)
DEB_KCOMPLETION_V ?= $(KCOMPLETION_VERSION)+ios1

kcompletion-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kcompletion))
	$(call EXTRACT_TAR,kcompletion-$(KF6_VERSION).tar.xz,kcompletion-$(KF6_VERSION),kcompletion)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kcompletion/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kcompletion/.build_complete),)
kcompletion:
	@echo "Using previously built kcompletion."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kcompletion: kcompletion-setup
	mkdir -p $(BUILD_WORK)/kcompletion/build
	cd $(BUILD_WORK)/kcompletion/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kcompletion/build
	+DESTDIR="$(BUILD_STAGE)/kcompletion" ninja -C $(BUILD_WORK)/kcompletion/build install
	$(call AFTER_BUILD,copy)
endif

kcompletion-package: kcompletion-stage
	rm -rf $(BUILD_DIST)/kf6-completion $(BUILD_DIST)/kf6-completion-dev
	$(call KF6_COPY_RUNTIME,kcompletion,kf6-completion)
	$(call KF6_COPY_DEV,kcompletion,kf6-completion)
	$(call SIGN,kf6-completion,general.xml)
	$(call SIGN,kf6-completion-dev,general.xml)
	$(call PACK,kf6-completion,DEB_KCOMPLETION_V)
	$(call PACK,kf6-completion-dev,DEB_KCOMPLETION_V)
	rm -rf $(BUILD_DIST)/kf6-completion $(BUILD_DIST)/kf6-completion-dev

.PHONY: kcompletion kcompletion-package
