ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kconfigwidgets
KCONFIGWIDGETS_VERSION = $(KF6_VERSION)
DEB_KCONFIGWIDGETS_V ?= $(KCONFIGWIDGETS_VERSION)+ios1

kconfigwidgets-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kconfigwidgets))
	$(call EXTRACT_TAR,kconfigwidgets-$(KF6_VERSION).tar.xz,kconfigwidgets-$(KF6_VERSION),kconfigwidgets)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kconfigwidgets/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kconfigwidgets/.build_complete),)
kconfigwidgets:
	@echo "Using previously built kconfigwidgets."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kconfigwidgets: kconfigwidgets-setup
	mkdir -p $(BUILD_WORK)/kconfigwidgets/build
	cd $(BUILD_WORK)/kconfigwidgets/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kconfigwidgets/build
	+DESTDIR="$(BUILD_STAGE)/kconfigwidgets" ninja -C $(BUILD_WORK)/kconfigwidgets/build install
	$(call AFTER_BUILD,copy)
endif

kconfigwidgets-package: kconfigwidgets-stage
	rm -rf $(BUILD_DIST)/kf6-configwidgets $(BUILD_DIST)/kf6-configwidgets-dev
	$(call KF6_COPY_RUNTIME,kconfigwidgets,kf6-configwidgets)
	$(call KF6_COPY_DEV,kconfigwidgets,kf6-configwidgets)
	$(call SIGN,kf6-configwidgets,general.xml)
	$(call SIGN,kf6-configwidgets-dev,general.xml)
	$(call PACK,kf6-configwidgets,DEB_KCONFIGWIDGETS_V)
	$(call PACK,kf6-configwidgets-dev,DEB_KCONFIGWIDGETS_V)
	rm -rf $(BUILD_DIST)/kf6-configwidgets $(BUILD_DIST)/kf6-configwidgets-dev

.PHONY: kconfigwidgets kconfigwidgets-package
