ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kconfig.mk — kf6-config for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Host-tooling provider (kconfig_compiler_kf6): nearly every KDE cmake project
# runs it at build time. Its Config.cmake takes the KF6_HOST_TOOLING branch
# when CMAKE_CROSSCOMPILING, the same mechanism Android KDE builds use.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kconfig
KCONFIG_VERSION = $(KF6_VERSION)
DEB_KCONFIG_V ?= $(KCONFIG_VERSION)

kconfig-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kconfig))
	$(call EXTRACT_TAR,kconfig-$(KF6_VERSION).tar.xz,kconfig-$(KF6_VERSION),kconfig)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kconfig/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kconfig/.build_complete),)
kconfig:
	@echo "Using previously built kconfig."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kconfig: kconfig-setup
	mkdir -p $(BUILD_WORK)/kconfig/build
	cd $(BUILD_WORK)/kconfig/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kconfig/build
	+DESTDIR="$(BUILD_STAGE)/kconfig" ninja -C $(BUILD_WORK)/kconfig/build install
	$(call AFTER_BUILD,copy)
endif

kconfig-package: kconfig-stage
	rm -rf $(BUILD_DIST)/kf6-config $(BUILD_DIST)/kf6-config-dev
	$(call KF6_COPY_RUNTIME,kconfig,kf6-config)
	$(call KF6_COPY_DEV,kconfig,kf6-config)
	$(call SIGN,kf6-config,general.xml)
	$(call SIGN,kf6-config-dev,general.xml)
	$(call PACK,kf6-config,DEB_KCONFIG_V)
	$(call PACK,kf6-config-dev,DEB_KCONFIG_V)
	rm -rf $(BUILD_DIST)/kf6-config $(BUILD_DIST)/kf6-config-dev

.PHONY: kconfig kconfig-package
