ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kcoreaddons.mk — kf6-coreaddons for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Host-tooling provider (desktoptojson): stage 1 of build-kf6.sh builds this
# natively; cross consumers resolve the tool via KF6_HOST_TOOLING.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kcoreaddons
KCOREADDONS_VERSION = $(KF6_VERSION)
DEB_KCOREADDONS_V ?= $(KCOREADDONS_VERSION)

kcoreaddons-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kcoreaddons))
	$(call EXTRACT_TAR,kcoreaddons-$(KF6_VERSION).tar.xz,kcoreaddons-$(KF6_VERSION),kcoreaddons)
	$(call QT6_WRITE_IOSEXEC_FIXUP)

ifneq ($(wildcard $(BUILD_WORK)/kcoreaddons/.build_complete),)
kcoreaddons:
	@echo "Using previously built kcoreaddons."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kcoreaddons: kcoreaddons-setup
	mkdir -p $(BUILD_WORK)/kcoreaddons/build
	cd $(BUILD_WORK)/kcoreaddons/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kcoreaddons/build
	+DESTDIR="$(BUILD_STAGE)/kcoreaddons" ninja -C $(BUILD_WORK)/kcoreaddons/build install
	$(call AFTER_BUILD,copy)
endif

kcoreaddons-package: kcoreaddons-stage
	rm -rf $(BUILD_DIST)/kf6-coreaddons $(BUILD_DIST)/kf6-coreaddons-dev
	$(call KF6_COPY_RUNTIME,kcoreaddons,kf6-coreaddons)
	$(call KF6_COPY_DEV,kcoreaddons,kf6-coreaddons)
	$(call SIGN,kf6-coreaddons,general.xml)
	$(call SIGN,kf6-coreaddons-dev,general.xml)
	$(call PACK,kf6-coreaddons,DEB_KCOREADDONS_V)
	$(call PACK,kf6-coreaddons-dev,DEB_KCOREADDONS_V)
	rm -rf $(BUILD_DIST)/kf6-coreaddons $(BUILD_DIST)/kf6-coreaddons-dev

.PHONY: kcoreaddons kcoreaddons-package
