ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kcrash.mk — kf6-crash for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# drkonqi is not in the subset; KCrash without it just forwards to the default
# signal handlers. In the subset because kwin and kglobalacceld link it.
# Qt6Test is only used by autotests but required unconditionally upstream;
# drop that find_package while BUILD_TESTING=OFF. The GL renderer metadata
# probe needs a complete QOpenGLContext/OpenGL enum set that this Qt iOS
# cross tree does not expose, so iOS returns empty renderer metadata.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kcrash
KCRASH_VERSION = $(KF6_VERSION)
DEB_KCRASH_V ?= $(KCRASH_VERSION)+ios1

kcrash-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kcrash))
	$(call EXTRACT_TAR,kcrash-$(KF6_VERSION).tar.xz,kcrash-$(KF6_VERSION),kcrash)
	sed -i '/find_package(Qt6Test/d' $(BUILD_WORK)/kcrash/CMakeLists.txt
	perl -0pi -e 's/(QString glRenderer\(\)\n\{\n)/$$1#ifdef Q_OS_IOS\n    return {};\n#else\n/' $(BUILD_WORK)/kcrash/src/kcrash.cpp
	sed -i '/GL_RENDERER)/a\#endif' $(BUILD_WORK)/kcrash/src/kcrash.cpp
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kcrash/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kcrash/.build_complete),)
kcrash:
	@echo "Using previously built kcrash."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kcrash: kcrash-setup
	mkdir -p $(BUILD_WORK)/kcrash/build
	cd $(BUILD_WORK)/kcrash/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kcrash/build
	+DESTDIR="$(BUILD_STAGE)/kcrash" ninja -C $(BUILD_WORK)/kcrash/build install
	$(call AFTER_BUILD,copy)
endif

kcrash-package: kcrash-stage
	rm -rf $(BUILD_DIST)/kf6-crash $(BUILD_DIST)/kf6-crash-dev
	$(call KF6_COPY_RUNTIME,kcrash,kf6-crash)
	$(call KF6_COPY_DEV,kcrash,kf6-crash)
	$(call SIGN,kf6-crash,general.xml)
	$(call SIGN,kf6-crash-dev,general.xml)
	$(call PACK,kf6-crash,DEB_KCRASH_V)
	$(call PACK,kf6-crash-dev,DEB_KCRASH_V)
	rm -rf $(BUILD_DIST)/kf6-crash $(BUILD_DIST)/kf6-crash-dev

.PHONY: kcrash kcrash-package
