ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Hard gate: qtbase must be the round-2 build (FEATURE_dbus=ON, plan Q3).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kdbusaddons
KDBUSADDONS_VERSION = $(KF6_VERSION)
DEB_KDBUSADDONS_V ?= $(KDBUSADDONS_VERSION)+ios1

kdbusaddons-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kdbusaddons))
	$(call EXTRACT_TAR,kdbusaddons-$(KF6_VERSION).tar.xz,kdbusaddons-$(KF6_VERSION),kdbusaddons)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kdbusaddons/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kdbusaddons/.build_complete),)
kdbusaddons:
	@echo "Using previously built kdbusaddons."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kdbusaddons: kdbusaddons-setup
	mkdir -p $(BUILD_WORK)/kdbusaddons/build
	cd $(BUILD_WORK)/kdbusaddons/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kdbusaddons/build
	+DESTDIR="$(BUILD_STAGE)/kdbusaddons" ninja -C $(BUILD_WORK)/kdbusaddons/build install
	$(call AFTER_BUILD,copy)
endif

kdbusaddons-package: kdbusaddons-stage
	rm -rf $(BUILD_DIST)/kf6-dbusaddons $(BUILD_DIST)/kf6-dbusaddons-dev
	$(call KF6_COPY_RUNTIME,kdbusaddons,kf6-dbusaddons)
	$(call KF6_COPY_DEV,kdbusaddons,kf6-dbusaddons)
	$(call SIGN,kf6-dbusaddons,general.xml)
	$(call SIGN,kf6-dbusaddons-dev,general.xml)
	$(call PACK,kf6-dbusaddons,DEB_KDBUSADDONS_V)
	$(call PACK,kf6-dbusaddons-dev,DEB_KDBUSADDONS_V)
	rm -rf $(BUILD_DIST)/kf6-dbusaddons $(BUILD_DIST)/kf6-dbusaddons-dev

.PHONY: kdbusaddons kdbusaddons-package
