ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Upstream skips KGlobalAccel on APPLE in its top-level CMakeLists.txt guard;
# this repo builds the full kglobalaccel chain, so the sed below widens that
# guard open. The only consumer (keysequencehelper.cpp) already guards behind
# HAVE_KGLOBALACCEL with no Q_OS check, so opening the CMake guard alone is
# sufficient; no source patch needed.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kdeclarative
KDECLARATIVE_VERSION = $(KF6_VERSION)
DEB_KDECLARATIVE_V ?= $(KDECLARATIVE_VERSION)+ios2

kdeclarative-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kdeclarative))
	$(call EXTRACT_TAR,kdeclarative-$(KF6_VERSION).tar.xz,kdeclarative-$(KF6_VERSION),kdeclarative)
	sed -i 's/if(NOT WIN32 AND NOT APPLE AND NOT ANDROID)/if(NOT WIN32 AND NOT ANDROID)/' $(BUILD_WORK)/kdeclarative/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kdeclarative/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kdeclarative/.build_complete),)
kdeclarative:
	@echo "Using previously built kdeclarative."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kdeclarative: kdeclarative-setup
	mkdir -p $(BUILD_WORK)/kdeclarative/build
	cd $(BUILD_WORK)/kdeclarative/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kdeclarative/build
	+DESTDIR="$(BUILD_STAGE)/kdeclarative" ninja -C $(BUILD_WORK)/kdeclarative/build install
	$(call AFTER_BUILD,copy)
endif

kdeclarative-package: kdeclarative-stage
	rm -rf $(BUILD_DIST)/kf6-declarative $(BUILD_DIST)/kf6-declarative-dev
	$(call KF6_COPY_RUNTIME,kdeclarative,kf6-declarative)
	$(call KF6_COPY_DEV,kdeclarative,kf6-declarative)
	$(call SIGN,kf6-declarative,general.xml)
	$(call SIGN,kf6-declarative-dev,general.xml)
	$(call PACK,kf6-declarative,DEB_KDECLARATIVE_V)
	$(call PACK,kf6-declarative-dev,DEB_KDECLARATIVE_V)
	rm -rf $(BUILD_DIST)/kf6-declarative $(BUILD_DIST)/kf6-declarative-dev

.PHONY: kdeclarative kdeclarative-package
