ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kdecoration.mk — kdecoration for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Plasma-released, version 6.1.5, library name KDecoration2 (KDecoration3 only
# exists from Plasma 6.3; the plan doc's earlier mention was wrong). kwin's
# server-side decoration support REQUIREs it even for the nested case.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kdecoration
KDECORATION_VERSION = $(PLASMA_VERSION)
DEB_KDECORATION_V ?= $(KDECORATION_VERSION)

kdecoration-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call PLASMA_URL,kdecoration))
	$(call EXTRACT_TAR,kdecoration-$(PLASMA_VERSION).tar.xz,kdecoration-$(PLASMA_VERSION),kdecoration)
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kdecoration/.build_complete),)
kdecoration:
	@echo "Using previously built kdecoration."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kdecoration: kdecoration-setup
	mkdir -p $(BUILD_WORK)/kdecoration/build
	cd $(BUILD_WORK)/kdecoration/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kdecoration/build
	+DESTDIR="$(BUILD_STAGE)/kdecoration" ninja -C $(BUILD_WORK)/kdecoration/build install
	$(call AFTER_BUILD,copy)
endif

kdecoration-package: kdecoration-stage
	rm -rf $(BUILD_DIST)/kdecoration $(BUILD_DIST)/kdecoration-dev
	$(call KF6_COPY_RUNTIME,kdecoration,kdecoration)
	$(call KF6_COPY_DEV,kdecoration,kdecoration)
	$(call SIGN,kdecoration,general.xml)
	$(call SIGN,kdecoration-dev,general.xml)
	$(call PACK,kdecoration,DEB_KDECORATION_V)
	$(call PACK,kdecoration-dev,DEB_KDECORATION_V)
	rm -rf $(BUILD_DIST)/kdecoration $(BUILD_DIST)/kdecoration-dev

.PHONY: kdecoration kdecoration-package
