ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kded.mk — kf6-kded for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Plasma Workspace expects KF6KDED. DocTools is optional and disabled for the
# bring-up package to avoid another host-tool/docs branch.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kded
KDED_VERSION = $(KF6_VERSION)
DEB_KDED_V ?= $(KDED_VERSION)+ios1

kded-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kded))
	$(call EXTRACT_TAR,kded-$(KF6_VERSION).tar.xz,kded-$(KF6_VERSION),kded)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kded/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kded/.build_complete),)
kded:
	@echo "Using previously built kded."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kded: kded-setup
	mkdir -p $(BUILD_WORK)/kded/build
	cd $(BUILD_WORK)/kded/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=TRUE
	+ninja -C $(BUILD_WORK)/kded/build
	+DESTDIR="$(BUILD_STAGE)/kded" ninja -C $(BUILD_WORK)/kded/build install
	$(call AFTER_BUILD,copy)
endif

kded-package: kded-stage
	rm -rf $(BUILD_DIST)/kf6-kded $(BUILD_DIST)/kf6-kded-dev
	$(call KF6_COPY_RUNTIME,kded,kf6-kded)
	$(call KF6_COPY_DEV,kded,kf6-kded)
	$(call SIGN,kf6-kded,general.xml)
	$(call SIGN,kf6-kded-dev,general.xml)
	$(call PACK,kf6-kded,DEB_KDED_V)
	$(call PACK,kf6-kded-dev,DEB_KDED_V)
	rm -rf $(BUILD_DIST)/kf6-kded $(BUILD_DIST)/kf6-kded-dev

.PHONY: kded kded-package
