ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kf6-common.mk — shared definitions for the KDE Frameworks 6 cross builds (layer K of
# docs/kde-plasma-plan.md: the framework tier between Qt 6 and KWin/Plasma). The per-
# framework recipes are generated by tools/gen-kf6-recipes.py from the K0 audit table;
# this file holds everything they share. All recursive (=) assignments: the main
# Makefile's `include makefiles/*.mk` glob sorts kcoreaddons.mk BEFORE kf6-common.mk,
# so immediate (:=) expansion here would hand the early recipes empty variables.
#
# A KF6 cross build = a plain cmake project that (a) finds Qt through the same staged
# build_base + QT_HOST_PATH machinery as the Qt module recipes (qt6-common.mk), (b)
# finds ECM + earlier frameworks in build_base via CMAKE_FIND_ROOT_PATH, and (c)
# resolves the KDE build-time TOOLS (kconfig_compiler_kf6, desktoptojson, kpackagetool6)
# through KF6_HOST_TOOLING — KDE's own cross mechanism, the same branch the Android
# builds take: a framework's *Config.cmake includes the HOST ToolingTargets file instead
# of the target one when CMAKE_CROSSCOMPILING is set. build-kf6.sh stage 1 populates the
# host tree with native builds of ECM + the tool-providing frameworks (kcoreaddons,
# kconfig, karchive, ki18n, kpackage) against the existing host Qt.

KF6_VERSION    = 6.3.0
KF6_MINOR      = 6.3
PLASMA_VERSION = 6.1.5
PWP_VERSION    = 1.13.0

# $(call KF6_URL,kcoreaddons) / $(call PLASMA_URL,kwayland) -> official tarball URLs.
# Same EXTRACT_TAR staleness warning as qt6-common.mk: on any version bump, rm -rf the
# build_work tree or you silently rebuild the old sources.
KF6_URL    = https://download.kde.org/stable/frameworks/$(KF6_MINOR)/$(1)-$(KF6_VERSION).tar.xz
PLASMA_URL = https://download.kde.org/stable/plasma/$(PLASMA_VERSION)/$(1)-$(PLASMA_VERSION).tar.xz

# Host KF6 tooling prefix (build-kf6.sh stage 1). The value handed to cmake is the
# lib/cmake dir, which is where the frameworks' Config files go looking for
# KF6*/KF6*ToolingTargets.cmake when cross-compiling.
KF6_HOST_TOOLING = $(BUILD_TOOLS)/kf6-host/lib/cmake

# Flags shared by every framework build. QT6_MODULE_CMAKE_FLAGS carries the whole
# Apple/Darwin story (rationale in qtbase.mk, recap in qt6-common.mk): deployment-target
# blanking, the xcrun-probe bypass, OBJC/OBJCXX flags, the libiosexec C++ fixup, and
# QT_HOST_PATH for Qt's host codegen (moc/qmlcachegen/qmltyperegistrar/qsb).
# KDE-specific additions:
#   - KF6_HOST_TOOLING: see above.
#   - KDE_INSTALL_* pins: ECMQueryQt asks the HOST qtpaths for install locations when
#     cross-compiling, which would leak host-prefix paths into the install layout. Pin
#     every dir we care about to the same layout the Qt module debs use (QML modules and
#     Qt plugins under lib/qt6/) so nothing depends on what ECMQueryQt answers.
#   - KDE_INSTALL_USE_QT_SYS_PATHS=OFF: same leak, other switch.
#   - BUILD_TESTING=OFF: ECM's option; also stops find_package(Qt6Test) escalation.
#   - CMAKE_DISABLE_FIND_PACKAGE_KF6DocTools: no docbook toolchain, no doc debs.
#   - WaylandScanner_EXECUTABLE pinned to the HOST binary (qtwayland.mk precedent,
#     f5cf809): the W0 wayland deb stages an arm64-iOS wayland-scanner into
#     build_base/usr/bin, and the cross find-root searches the sysroot first ->
#     "Exec format error" at codegen. ECM's FindWaylandScanner is a plain
#     find_program(WaylandScanner_EXECUTABLE ...), so the -D pre-set wins. Affects
#     every protocol-codegen unit (kguiaddons/kidletime/kwayland/layer-shell-qt);
#     harmless for units that never look the scanner up. The /usr/bin copy exists
#     because build-kf6.sh apt-installs libwayland-bin every run. (The HOST
#     qtwaylandscanner is the separate QT_HOST_PATH mechanism, already gated.)
#   - KF_IGNORE_PLATFORM_CHECK: ECM's KDEMetaInfoPlatformCheck (pulled in by
#     KDEFrameworkCompilerSettings, which the DBus/X11-touching frameworks from
#     kglobalaccel onward include) hard-FATALs on any platform outside Linux;FreeBSD —
#     Darwin is rejected. The error message names this exact escape hatch. Harmless for
#     the tier-1 units that don't run the check. (Host builds run natively on Linux, so
#     they pass without it.)
#   - GETTEXT_*_EXECUTABLE pinned to HOST tools: cross find-root otherwise discovers
#     the staged iOS msgfmt/msgmerge under build_base/usr/bin, then ki18n tries to run
#     target Mach-O binaries while generating .mo files.
KF6_CMAKE_FLAGS = \
	$(QT6_MODULE_CMAKE_FLAGS) \
	-DWaylandScanner_EXECUTABLE=/usr/bin/wayland-scanner \
	-DGETTEXT_MSGFMT_EXECUTABLE=/usr/bin/msgfmt \
	-DGETTEXT_MSGMERGE_EXECUTABLE=/usr/bin/msgmerge \
	-DGETTEXT_XGETTEXT_EXECUTABLE=/usr/bin/xgettext \
	-DKF_IGNORE_PLATFORM_CHECK=TRUE \
	-DKF6_HOST_TOOLING=$(KF6_HOST_TOOLING) \
	-DBUILD_TESTING=OFF \
	-DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=TRUE \
	-DKDE_INSTALL_USE_QT_SYS_PATHS=OFF \
	-DKDE_INSTALL_LIBDIR=lib \
	-DKDE_INSTALL_INCLUDEDIR=include \
	-DKDE_INSTALL_LIBEXECDIR=libexec \
	-DKDE_INSTALL_DATADIR=share \
	-DKDE_INSTALL_QMLDIR=lib/qt6/qml \
	-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins \
	-DKDE_INSTALL_PLUGINDIR=lib/qt6/plugins

# Packaging split, one shell line each so the generated recipes stay short.
# Runtime deb: dylibs, Qt plugins + QML modules, runtime tools (bin/ holds things like
# kbuildsycoca6 that genuinely run on device — unlike the Qt recipes, where bin/ is
# host-shaped tooling and goes to -dev), daemons in libexec/, and share/ data (locale,
# framework data files) minus man/doc.
# $(call KF6_COPY_RUNTIME,<build_work name>,<deb name>)
KF6_COPY_RUNTIME = \
	src=$(BUILD_STAGE)/$(1)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	dst=$(BUILD_DIST)/$(2)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	mkdir -p $$dst/lib; \
	cp -a $$src/lib/*.dylib $$dst/lib/ 2>/dev/null || true; \
	for d in bin libexec share lib/qt6/plugins lib/qt6/qml; do \
		if [ -e "$$src/$$d" ]; then \
			mkdir -p "$$dst/$$(dirname $$d)"; \
			cp -a "$$src/$$d" "$$dst/$$d"; \
		fi; \
	done; \
	rm -rf $$dst/share/man $$dst/share/doc

# Dev deb: headers, cmake packages, pkgconfig, Qt metatypes glue.
# $(call KF6_COPY_DEV,<build_work name>,<deb name>)
KF6_COPY_DEV = \
	src=$(BUILD_STAGE)/$(1)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	dst=$(BUILD_DIST)/$(2)-dev/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	mkdir -p $$dst; \
	for d in include lib/cmake lib/pkgconfig lib/metatypes; do \
		if [ -e "$$src/$$d" ]; then \
			mkdir -p "$$dst/$$(dirname $$d)"; \
			cp -a "$$src/$$d" "$$dst/$$d"; \
		fi; \
	done

# Whole staged prefix into a single deb (data-only packages: ECM, breeze-icons,
# plasma-wayland-protocols — cmake configs included so cross consumers still resolve
# them from the installed deb layout mirrored into build_base).
# $(call KF6_COPY_ALL,<build_work name>,<deb name>)
KF6_COPY_ALL = \
	src=$(BUILD_STAGE)/$(1)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	dst=$(BUILD_DIST)/$(2)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	mkdir -p $$dst; \
	cp -a $$src/. $$dst/; \
	rm -rf $$dst/share/man $$dst/share/doc
