ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Shared by the per-framework recipes (generated by tools/gen-kf6-recipes.py
# from the K0 audit table). Must use recursive (=) assignment: the Makefile's
# `include makefiles/*.mk` glob sorts kcoreaddons.mk before this file, so
# immediate (:=) expansion here would hand the early recipes empty variables.
#
# KF6_HOST_TOOLING resolves build-time tools (kconfig_compiler_kf6,
# desktoptojson, kpackagetool6) via KDE's cross mechanism: a framework's
# *Config.cmake includes the HOST ToolingTargets file instead of the target
# one when CMAKE_CROSSCOMPILING is set (same branch Android builds take).
# build-kf6.sh stage 1 populates the host tree with native builds of ECM and
# the tool-providing frameworks against the existing host Qt.

KF6_VERSION    = 6.3.0
KF6_MINOR      = 6.3
PLASMA_VERSION = 6.1.5
PWP_VERSION    = 1.13.0

# On any version bump, rm -rf the build_work tree first, or you'll silently
# rebuild the old sources (same EXTRACT_TAR staleness issue as qt6-common.mk).
KF6_URL    = https://download.kde.org/stable/frameworks/$(KF6_MINOR)/$(1)-$(KF6_VERSION).tar.xz
PLASMA_URL = https://download.kde.org/stable/plasma/$(PLASMA_VERSION)/$(1)-$(PLASMA_VERSION).tar.xz

# lib/cmake dir: where frameworks' Config files look for
# KF6*/KF6*ToolingTargets.cmake when cross-compiling.
KF6_HOST_TOOLING = $(BUILD_TOOLS)/kf6-host/lib/cmake

# Flags shared by every framework build (Darwin bits live in QT6_MODULE_CMAKE_FLAGS, see qtbase.mk).
# HOST-tool pins (WaylandScanner/GETTEXT) stop the cross find-root from grabbing staged iOS
# binaries (Exec format error / wrong-arch .mo gen). ECM's Qt query also needs the host
# qtpaths binary: the target CoreTools package intentionally contains no executable that
# can run in the Linux builder. KDE_INSTALL_* pins keep its answers from becoming install
# paths when cross-compiling.
KF6_CMAKE_FLAGS = \
	$(QT6_MODULE_CMAKE_FLAGS) \
	-DQUERY_EXECUTABLE=$(QT6_HOST_PATH)/bin/qtpaths \
	-DWaylandScanner_EXECUTABLE=/usr/bin/wayland-scanner \
	-DGETTEXT_MSGFMT_EXECUTABLE=/usr/bin/msgfmt \
	-DGETTEXT_MSGMERGE_EXECUTABLE=/usr/bin/msgmerge \
	-DGETTEXT_XGETTEXT_EXECUTABLE=/usr/bin/xgettext \
	-DKF_IGNORE_PLATFORM_CHECK=TRUE \
	-DKF6_HOST_TOOLING=$(KF6_HOST_TOOLING) \
	-DBUILD_TESTING=OFF \
	-DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=TRUE \
	-DKDE_INSTALL_USE_QT_SYS_PATHS=OFF \
	-DKDE_INSTALL_LIBDIR=lib \
	-DKDE_INSTALL_INCLUDEDIR=include \
	-DKDE_INSTALL_LIBEXECDIR=libexec \
	-DKDE_INSTALL_DATADIR=share \
	-DKDE_INSTALL_QMLDIR=lib/qt6/qml \
	-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins \
	-DKDE_INSTALL_PLUGINDIR=lib/qt6/plugins

# bin/ here holds runtime tools that actually run on device (e.g.
# kbuildsycoca6), unlike the Qt recipes, where bin/ is host tooling and goes
# to -dev.
# $(call KF6_COPY_RUNTIME,<build_work name>,<deb name>)
KF6_COPY_RUNTIME = \
	src=$(BUILD_STAGE)/$(1)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	dst=$(BUILD_DIST)/$(2)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	mkdir -p $$dst/lib; \
	cp -a $$src/lib/*.dylib $$dst/lib/ 2>/dev/null || true; \
	for d in bin libexec share lib/qt6/plugins lib/qt6/qml; do \
		if [ -e "$$src/$$d" ]; then \
			mkdir -p "$$dst/$$(dirname $$d)"; \
			cp -a "$$src/$$d" "$$dst/$$d"; \
		fi; \
	done; \
	rm -rf $$dst/share/man $$dst/share/doc

# $(call KF6_COPY_DEV,<build_work name>,<deb name>)
KF6_COPY_DEV = \
	src=$(BUILD_STAGE)/$(1)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	dst=$(BUILD_DIST)/$(2)-dev/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	mkdir -p $$dst; \
	for d in include lib/cmake lib/pkgconfig lib/metatypes; do \
		if [ -e "$$src/$$d" ]; then \
			mkdir -p "$$dst/$$(dirname $$d)"; \
			cp -a "$$src/$$d" "$$dst/$$d"; \
		fi; \
	done

# Whole staged prefix in one deb (ECM, breeze-icons, plasma-wayland-protocols):
# cmake configs stay in so cross consumers can still resolve them from
# build_base.
# $(call KF6_COPY_ALL,<build_work name>,<deb name>)
KF6_COPY_ALL = \
	src=$(BUILD_STAGE)/$(1)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	dst=$(BUILD_DIST)/$(2)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX); \
	mkdir -p $$dst; \
	cp -a $$src/. $$dst/; \
	rm -rf $$dst/share/man $$dst/share/doc
