ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kwin requires this unless built with KWIN_BUILD_GLOBALSHORTCUTS=OFF. Even
# with kcms off, kwin's runtime still needs the KIO chain through this daemon.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kglobalacceld
KGLOBALACCELD_VERSION = $(PLASMA_VERSION)
DEB_KGLOBALACCELD_V ?= $(KGLOBALACCELD_VERSION)+ios1

kglobalacceld-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call PLASMA_URL,kglobalacceld))
	$(call EXTRACT_TAR,kglobalacceld-$(PLASMA_VERSION).tar.xz,kglobalacceld-$(PLASMA_VERSION),kglobalacceld)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kglobalacceld/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kglobalacceld/.build_complete),)
kglobalacceld:
	@echo "Using previously built kglobalacceld."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kglobalacceld: kglobalacceld-setup
	mkdir -p $(BUILD_WORK)/kglobalacceld/build
	cd $(BUILD_WORK)/kglobalacceld/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kglobalacceld/build
	+DESTDIR="$(BUILD_STAGE)/kglobalacceld" ninja -C $(BUILD_WORK)/kglobalacceld/build install
	$(call AFTER_BUILD,copy)
endif

kglobalacceld-package: kglobalacceld-stage
	rm -rf $(BUILD_DIST)/kglobalacceld $(BUILD_DIST)/kglobalacceld-dev
	$(call KF6_COPY_RUNTIME,kglobalacceld,kglobalacceld)
	$(call KF6_COPY_DEV,kglobalacceld,kglobalacceld)
	$(call SIGN,kglobalacceld,general.xml)
	$(call SIGN,kglobalacceld-dev,general.xml)
	$(call PACK,kglobalacceld,DEB_KGLOBALACCELD_V)
	$(call PACK,kglobalacceld-dev,DEB_KGLOBALACCELD_V)
	rm -rf $(BUILD_DIST)/kglobalacceld $(BUILD_DIST)/kglobalacceld-dev

.PHONY: kglobalacceld kglobalacceld-package
