ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kglobalaccel.mk — kf6-globalaccel for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Client half only; the daemon moved to the Plasma-released kglobalacceld
# (built later in this layer). On Wayland the compositor (kwin) does the
# actual grabbing.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kglobalaccel
KGLOBALACCEL_VERSION = $(KF6_VERSION)
DEB_KGLOBALACCEL_V ?= $(KGLOBALACCEL_VERSION)+ios1

kglobalaccel-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kglobalaccel))
	$(call EXTRACT_TAR,kglobalaccel-$(KF6_VERSION).tar.xz,kglobalaccel-$(KF6_VERSION),kglobalaccel)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kglobalaccel/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kglobalaccel/.build_complete),)
kglobalaccel:
	@echo "Using previously built kglobalaccel."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kglobalaccel: kglobalaccel-setup
	mkdir -p $(BUILD_WORK)/kglobalaccel/build
	cd $(BUILD_WORK)/kglobalaccel/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kglobalaccel/build
	+DESTDIR="$(BUILD_STAGE)/kglobalaccel" ninja -C $(BUILD_WORK)/kglobalaccel/build install
	$(call AFTER_BUILD,copy)
endif

kglobalaccel-package: kglobalaccel-stage
	rm -rf $(BUILD_DIST)/kf6-globalaccel $(BUILD_DIST)/kf6-globalaccel-dev
	$(call KF6_COPY_RUNTIME,kglobalaccel,kf6-globalaccel)
	$(call KF6_COPY_DEV,kglobalaccel,kf6-globalaccel)
	$(call SIGN,kf6-globalaccel,general.xml)
	$(call SIGN,kf6-globalaccel-dev,general.xml)
	$(call PACK,kf6-globalaccel,DEB_KGLOBALACCEL_V)
	$(call PACK,kf6-globalaccel-dev,DEB_KGLOBALACCEL_V)
	rm -rf $(BUILD_DIST)/kf6-globalaccel $(BUILD_DIST)/kf6-globalaccel-dev

.PHONY: kglobalaccel kglobalaccel-package
