ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kguiaddons.mk — kf6-guiaddons for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# APPLE guards audited against the real v6.3.0 tree and pre-patched in -setup:
# (1) the top-level 'UNIX AND NOT APPLE' guard hard-sets WITH_WAYLAND/X11/DBUS
# OFF on APPLE before the -D flags can win, so APPLE is let into the UNIX
# branch; (2) src/CMakeLists.txt if(APPLE) adds kcolorschemewatcher_mac.mm +
# links AppKit (absent on iPhoneOS) -> forced off; the runtime picker compiles
# the xdg/DBus watcher because Qt for iOS defines Q_OS_IOS, not Q_OS_MACOS.
# Wayland codegen (keystate/wlr-data-control/shortcut-inhibit) runs the HOST
# qtwaylandscanner via QT_HOST_PATH, and Wayland_DATADIR must resolve to the
# staged wayland deb's share/wayland/wayland.xml.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kguiaddons
KGUIADDONS_VERSION = $(KF6_VERSION)
DEB_KGUIADDONS_V ?= $(KGUIADDONS_VERSION)+ios1

kguiaddons-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kguiaddons))
	$(call EXTRACT_TAR,kguiaddons-$(KF6_VERSION).tar.xz,kguiaddons-$(KF6_VERSION),kguiaddons)
	sed -i 's/if (UNIX AND NOT ANDROID AND NOT APPLE)/if (UNIX AND NOT ANDROID)/' $(BUILD_WORK)/kguiaddons/CMakeLists.txt
	sed -i 's/^if(APPLE)$$/if(FALSE) # iOS: no AppKit/' $(BUILD_WORK)/kguiaddons/src/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kguiaddons/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kguiaddons/.build_complete),)
kguiaddons:
	@echo "Using previously built kguiaddons."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kguiaddons: kguiaddons-setup
	mkdir -p $(BUILD_WORK)/kguiaddons/build
	cd $(BUILD_WORK)/kguiaddons/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DWITH_WAYLAND=ON \
		-DWITH_X11=OFF \
		-DWITH_DBUS=ON
	+ninja -C $(BUILD_WORK)/kguiaddons/build
	+DESTDIR="$(BUILD_STAGE)/kguiaddons" ninja -C $(BUILD_WORK)/kguiaddons/build install
	$(call AFTER_BUILD,copy)
endif

kguiaddons-package: kguiaddons-stage
	rm -rf $(BUILD_DIST)/kf6-guiaddons $(BUILD_DIST)/kf6-guiaddons-dev
	$(call KF6_COPY_RUNTIME,kguiaddons,kf6-guiaddons)
	$(call KF6_COPY_DEV,kguiaddons,kf6-guiaddons)
	$(call SIGN,kf6-guiaddons,general.xml)
	$(call SIGN,kf6-guiaddons-dev,general.xml)
	$(call PACK,kf6-guiaddons,DEB_KGUIADDONS_V)
	$(call PACK,kf6-guiaddons-dev,DEB_KGUIADDONS_V)
	rm -rf $(BUILD_DIST)/kf6-guiaddons $(BUILD_DIST)/kf6-guiaddons-dev

.PHONY: kguiaddons kguiaddons-package
