ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kguiaddons.mk — kf6-guiaddons for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# APPLE-branch risk (audit): we build with CMAKE_SYSTEM_NAME=Darwin, and KDE
# cmake treats APPLE as macOS. WITH_WAYLAND is forced ON so the wayland
# integration kwin needs cannot be silently dropped by an if(APPLE) guard;
# if the guard is a hard one, sed it in phase 2.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kguiaddons
KGUIADDONS_VERSION = $(KF6_VERSION)
DEB_KGUIADDONS_V ?= $(KGUIADDONS_VERSION)

kguiaddons-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kguiaddons))
	$(call EXTRACT_TAR,kguiaddons-$(KF6_VERSION).tar.xz,kguiaddons-$(KF6_VERSION),kguiaddons)
	$(call QT6_WRITE_IOSEXEC_FIXUP)

ifneq ($(wildcard $(BUILD_WORK)/kguiaddons/.build_complete),)
kguiaddons:
	@echo "Using previously built kguiaddons."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kguiaddons: kguiaddons-setup
	mkdir -p $(BUILD_WORK)/kguiaddons/build
	cd $(BUILD_WORK)/kguiaddons/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DWITH_WAYLAND=ON \
		-DWITH_X11=OFF
	+ninja -C $(BUILD_WORK)/kguiaddons/build
	+DESTDIR="$(BUILD_STAGE)/kguiaddons" ninja -C $(BUILD_WORK)/kguiaddons/build install
	$(call AFTER_BUILD,copy)
endif

kguiaddons-package: kguiaddons-stage
	rm -rf $(BUILD_DIST)/kf6-guiaddons $(BUILD_DIST)/kf6-guiaddons-dev
	$(call KF6_COPY_RUNTIME,kguiaddons,kf6-guiaddons)
	$(call KF6_COPY_DEV,kguiaddons,kf6-guiaddons)
	$(call SIGN,kf6-guiaddons,general.xml)
	$(call SIGN,kf6-guiaddons-dev,general.xml)
	$(call PACK,kf6-guiaddons,DEB_KGUIADDONS_V)
	$(call PACK,kf6-guiaddons-dev,DEB_KGUIADDONS_V)
	rm -rf $(BUILD_DIST)/kf6-guiaddons $(BUILD_DIST)/kf6-guiaddons-dev

.PHONY: kguiaddons kguiaddons-package
