ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# ki18n.mk — kf6-i18n for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# libintl comes from the proxy-libintl deb (libgtkintl), the same precedent
# as the GTK stack. Needs python3 + gettext on the build host. iso-codes
# (deb exists) feeds language name lookups at runtime.
# Host build is a dependency of host kpackage (stage 1).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += ki18n
KI18N_VERSION = $(KF6_VERSION)
DEB_KI18N_V ?= $(KI18N_VERSION)

ki18n-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,ki18n))
	$(call EXTRACT_TAR,ki18n-$(KF6_VERSION).tar.xz,ki18n-$(KF6_VERSION),ki18n)
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/ki18n/.build_complete),)
ki18n:
	@echo "Using previously built ki18n."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
ki18n: ki18n-setup
	mkdir -p $(BUILD_WORK)/ki18n/build
	cd $(BUILD_WORK)/ki18n/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/ki18n/build
	+DESTDIR="$(BUILD_STAGE)/ki18n" ninja -C $(BUILD_WORK)/ki18n/build install
	$(call AFTER_BUILD,copy)
endif

ki18n-package: ki18n-stage
	rm -rf $(BUILD_DIST)/kf6-i18n $(BUILD_DIST)/kf6-i18n-dev
	$(call KF6_COPY_RUNTIME,ki18n,kf6-i18n)
	$(call KF6_COPY_DEV,ki18n,kf6-i18n)
	$(call SIGN,kf6-i18n,general.xml)
	$(call SIGN,kf6-i18n-dev,general.xml)
	$(call PACK,kf6-i18n,DEB_KI18N_V)
	$(call PACK,kf6-i18n-dev,DEB_KI18N_V)
	rm -rf $(BUILD_DIST)/kf6-i18n $(BUILD_DIST)/kf6-i18n-dev

.PHONY: ki18n ki18n-package
