ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kiconthemes.mk — kf6-iconthemes for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kiconthemes
KICONTHEMES_VERSION = $(KF6_VERSION)
DEB_KICONTHEMES_V ?= $(KICONTHEMES_VERSION)

kiconthemes-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kiconthemes))
	$(call EXTRACT_TAR,kiconthemes-$(KF6_VERSION).tar.xz,kiconthemes-$(KF6_VERSION),kiconthemes)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kiconthemes/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kiconthemes/.build_complete),)
kiconthemes:
	@echo "Using previously built kiconthemes."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kiconthemes: kiconthemes-setup
	mkdir -p $(BUILD_WORK)/kiconthemes/build
	cd $(BUILD_WORK)/kiconthemes/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kiconthemes/build
	+DESTDIR="$(BUILD_STAGE)/kiconthemes" ninja -C $(BUILD_WORK)/kiconthemes/build install
	$(call AFTER_BUILD,copy)
endif

kiconthemes-package: kiconthemes-stage
	rm -rf $(BUILD_DIST)/kf6-iconthemes $(BUILD_DIST)/kf6-iconthemes-dev
	$(call KF6_COPY_RUNTIME,kiconthemes,kf6-iconthemes)
	$(call KF6_COPY_DEV,kiconthemes,kf6-iconthemes)
	$(call SIGN,kf6-iconthemes,general.xml)
	$(call SIGN,kf6-iconthemes-dev,general.xml)
	$(call PACK,kf6-iconthemes,DEB_KICONTHEMES_V)
	$(call PACK,kf6-iconthemes-dev,DEB_KICONTHEMES_V)
	rm -rf $(BUILD_DIST)/kf6-iconthemes $(BUILD_DIST)/kf6-iconthemes-dev

.PHONY: kiconthemes kiconthemes-package
