ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kidletime.mk — kf6-idletime for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# APPLE-branch risk: the mac idle poller uses ApplicationServices APIs that do
# not exist on iPhoneOS. Expect a phase-2 patch that forces the wayland
# (ext-idle-notify) poller and drops the mac one.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kidletime
KIDLETIME_VERSION = $(KF6_VERSION)
DEB_KIDLETIME_V ?= $(KIDLETIME_VERSION)

kidletime-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kidletime))
	$(call EXTRACT_TAR,kidletime-$(KF6_VERSION).tar.xz,kidletime-$(KF6_VERSION),kidletime)
	$(call QT6_WRITE_IOSEXEC_FIXUP)

ifneq ($(wildcard $(BUILD_WORK)/kidletime/.build_complete),)
kidletime:
	@echo "Using previously built kidletime."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kidletime: kidletime-setup
	mkdir -p $(BUILD_WORK)/kidletime/build
	cd $(BUILD_WORK)/kidletime/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kidletime/build
	+DESTDIR="$(BUILD_STAGE)/kidletime" ninja -C $(BUILD_WORK)/kidletime/build install
	$(call AFTER_BUILD,copy)
endif

kidletime-package: kidletime-stage
	rm -rf $(BUILD_DIST)/kf6-idletime $(BUILD_DIST)/kf6-idletime-dev
	$(call KF6_COPY_RUNTIME,kidletime,kf6-idletime)
	$(call KF6_COPY_DEV,kidletime,kf6-idletime)
	$(call SIGN,kf6-idletime,general.xml)
	$(call SIGN,kf6-idletime-dev,general.xml)
	$(call PACK,kf6-idletime,DEB_KIDLETIME_V)
	$(call PACK,kf6-idletime-dev,DEB_KIDLETIME_V)
	rm -rf $(BUILD_DIST)/kf6-idletime $(BUILD_DIST)/kf6-idletime-dev

.PHONY: kidletime kidletime-package
