ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# APPLE guards patched in -setup: the 'APPLE OR WIN32' block hard-sets
# WITH_WAYLAND OFF, the Carbon framework probe is dropped (no Carbon on
# iPhoneOS), and the osx idle poller plugin (Carbon/ApplicationServices) is
# removed from src/plugins. The wayland (ext-idle-notify) poller builds
# instead; its protocol codegen runs the HOST qtwaylandscanner via
# QT_HOST_PATH.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kidletime
KIDLETIME_VERSION = $(KF6_VERSION)
DEB_KIDLETIME_V ?= $(KIDLETIME_VERSION)+ios1

kidletime-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kidletime))
	$(call EXTRACT_TAR,kidletime-$(KF6_VERSION).tar.xz,kidletime-$(KF6_VERSION),kidletime)
	sed -i '/set(WITH_WAYLAND OFF)/d' $(BUILD_WORK)/kidletime/CMakeLists.txt
	sed -i '/cmake_find_frameworks(CoreFoundation Carbon)/d' $(BUILD_WORK)/kidletime/CMakeLists.txt
	sed -i '/add_subdirectory(osx)/d' $(BUILD_WORK)/kidletime/src/plugins/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kidletime/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kidletime/.build_complete),)
kidletime:
	@echo "Using previously built kidletime."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kidletime: kidletime-setup
	mkdir -p $(BUILD_WORK)/kidletime/build
	cd $(BUILD_WORK)/kidletime/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DWITH_WAYLAND=ON \
		-DWITH_X11=OFF
	+ninja -C $(BUILD_WORK)/kidletime/build
	+DESTDIR="$(BUILD_STAGE)/kidletime" ninja -C $(BUILD_WORK)/kidletime/build install
	$(call AFTER_BUILD,copy)
endif

kidletime-package: kidletime-stage
	rm -rf $(BUILD_DIST)/kf6-idletime $(BUILD_DIST)/kf6-idletime-dev
	$(call KF6_COPY_RUNTIME,kidletime,kf6-idletime)
	$(call KF6_COPY_DEV,kidletime,kf6-idletime)
	$(call SIGN,kf6-idletime,general.xml)
	$(call SIGN,kf6-idletime-dev,general.xml)
	$(call PACK,kf6-idletime,DEB_KIDLETIME_V)
	$(call PACK,kf6-idletime-dev,DEB_KIDLETIME_V)
	rm -rf $(BUILD_DIST)/kf6-idletime $(BUILD_DIST)/kf6-idletime-dev

.PHONY: kidletime kidletime-package
