ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kio.mk — kf6-kio for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# The widest framework in the subset; unavoidable, libplasma and kglobalacceld
# both REQUIRE it. Darwin spares us two Linux-isms (audited): LibMount is
# Linux-guarded (KMountPoint uses getmntinfo, present in the iOS libc) and X11
# integration is APPLE-guarded off. Qt6Core5Compat (QTextCodec) is REQUIRED,
# hence the qt6-5compat module dep - one of the three Qt module gaps the audit
# opened against the Qt layer. Qt6Test is only used by KIO's test programs;
# drop it from the unconditional Qt component list while BUILD_TESTING=OFF.
# Plasma Workspace's real desktop:/ worker needs KIOCore's DBus-gated
# ForwardingWorkerBase/KDirNotify sources, so the iOS build uses the Unix
# QtDBus branch instead of upstream's broad APPLE exclusion.
# Enabling that branch exposes kiod; keep kiod6 but drop the macOS AppKit
# LSUIElement agent/link path because the iPhoneOS SDK has no AppKit.
# ios3: the old fix collapsed BOTH src/kiod/CMakeLists.txt if(APPLE) guards
# to if(FALSE) via one blanket sed. That silenced the AppKit agent as intended
# but ALSO skipped the second guard's ecm_mark_nongui_executable(kiod6) call,
# so kiod6 built as a MACOSX_BUNDLE (kiod6.app/kiod6) while every kiod6 D-Bus
# service file (org.kde.kiod6/kssld6/kpasswdserver6/kioexecd6, all four - kssld,
# kpasswdserver and kioexecd are kiod PLUGINS loaded by the kiod6 host, not
# separate binaries, so upstream correctly points all four Execs at kiod6) still
# pointed Exec= at the plain path, so D-Bus activation silently failed on device.
# Two targeted deletions replace the blanket guard-kill: drop the kiod_agent.mm
# source line (first guard, harmless no-op target_sources once empty) and the
# AppKit/CoreFoundation target_link_libraries line (second guard), leaving both
# if(APPLE) blocks intact so ecm_mark_nongui_executable(kiod6) still runs (APPLE
# is TRUE for the iOS cross-compile target too) and kiod6 installs as a plain
# binary at libexec/kf6/kiod6, matching every service file - same mechanism kded6
# already uses unconditionally (see kded.mk/kded's CMakeLists.txt).
# KIOGui's file-manager DBus strategy has a Linux/FreeBSD declaration guard
# but source-level WITH_QTDBUS use, so include Q_OS_IOS in that guard.
# The file worker's NTFS hidden-attribute helper already has Darwin getxattr()
# arguments but upstream guards it as Q_OS_MACOS-only; include Q_OS_IOS too.
# The trash worker's macOS DiskArbitration branch is unavailable in the
# iPhoneOS SDK, so keep the worker on the generic Solid/stat path.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kio
KIO_VERSION = $(KF6_VERSION)
DEB_KIO_V ?= $(KIO_VERSION)+ios3

kio-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kio))
	$(call EXTRACT_TAR,kio-$(KF6_VERSION).tar.xz,kio-$(KF6_VERSION),kio)
	sed -i 's/if(UNIX AND NOT APPLE AND NOT ANDROID)/if(UNIX AND NOT ANDROID)/' $(BUILD_WORK)/kio/CMakeLists.txt
	sed -i '/kiod_agent\.mm/d' $(BUILD_WORK)/kio/src/kiod/CMakeLists.txt
	sed -i '/-framework AppKit -framework CoreFoundation/d' $(BUILD_WORK)/kio/src/kiod/CMakeLists.txt
	sed -i 's/defined(Q_OS_LINUX) || defined(Q_OS_FREEBSD)/defined(Q_OS_LINUX) || defined(Q_OS_FREEBSD) || defined(Q_OS_IOS)/' $(BUILD_WORK)/kio/src/gui/openfilemanagerwindowjob_p.h
	sed -i 's/ Widgets Network Concurrent Xml Test)/ Widgets Network Concurrent Xml)/' $(BUILD_WORK)/kio/CMakeLists.txt
	sed -i 's/#ifdef Q_OS_MACOS/#if defined(Q_OS_MACOS) || defined(Q_OS_IOS)/' $(BUILD_WORK)/kio/src/kioworkers/file/file_unix.cpp
	sed -i 's/Q_OS_OSX/Q_OS_MACOS/g' $(BUILD_WORK)/kio/src/kioworkers/trash/trashimpl.cpp
	sed -i 's/-framework DiskArbitration //' $(BUILD_WORK)/kio/src/kioworkers/trash/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kio/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kio/.build_complete),)
kio:
	@echo "Using previously built kio."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kio: kio-setup
	mkdir -p $(BUILD_WORK)/kio/build
	cd $(BUILD_WORK)/kio/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DCMAKE_DISABLE_FIND_PACKAGE_ACL=TRUE \
		-DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=TRUE
	+ninja -C $(BUILD_WORK)/kio/build
	+DESTDIR="$(BUILD_STAGE)/kio" ninja -C $(BUILD_WORK)/kio/build install
	$(call AFTER_BUILD,copy)
endif

kio-package: kio-stage
	rm -rf $(BUILD_DIST)/kf6-kio $(BUILD_DIST)/kf6-kio-dev
	$(call KF6_COPY_RUNTIME,kio,kf6-kio)
	$(call KF6_COPY_DEV,kio,kf6-kio)
	$(call SIGN,kf6-kio,general.xml)
	$(call SIGN,kf6-kio-dev,general.xml)
	$(call PACK,kf6-kio,DEB_KIO_V)
	$(call PACK,kf6-kio-dev,DEB_KIO_V)
	rm -rf $(BUILD_DIST)/kf6-kio $(BUILD_DIST)/kf6-kio-dev

.PHONY: kio kio-package
