ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kirigami.mk — kf6-kirigami for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Plasma Mobile's UI toolkit and, since KF6, the KirigamiPlatform package that
# KSvg and libplasma hard-require. Shaders bake at build time through the host
# qsb (QT_HOST_PATH); the cross Qt6ShaderTools cmake package must be staged
# (qtshadertools recipe).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kirigami
KIRIGAMI_VERSION = $(KF6_VERSION)
DEB_KIRIGAMI_V ?= $(KIRIGAMI_VERSION)+ios1

kirigami-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kirigami))
	$(call EXTRACT_TAR,kirigami-$(KF6_VERSION).tar.xz,kirigami-$(KF6_VERSION),kirigami)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kirigami/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kirigami/.build_complete),)
kirigami:
	@echo "Using previously built kirigami."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kirigami: kirigami-setup
	mkdir -p $(BUILD_WORK)/kirigami/build
	cd $(BUILD_WORK)/kirigami/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kirigami/build
	+DESTDIR="$(BUILD_STAGE)/kirigami" ninja -C $(BUILD_WORK)/kirigami/build install
	$(call AFTER_BUILD,copy)
endif

kirigami-package: kirigami-stage
	rm -rf $(BUILD_DIST)/kf6-kirigami $(BUILD_DIST)/kf6-kirigami-dev
	$(call KF6_COPY_RUNTIME,kirigami,kf6-kirigami)
	$(call KF6_COPY_DEV,kirigami,kf6-kirigami)
	$(call SIGN,kf6-kirigami,general.xml)
	$(call SIGN,kf6-kirigami-dev,general.xml)
	$(call PACK,kf6-kirigami,DEB_KIRIGAMI_V)
	$(call PACK,kf6-kirigami-dev,DEB_KIRIGAMI_V)
	rm -rf $(BUILD_DIST)/kf6-kirigami $(BUILD_DIST)/kf6-kirigami-dev

.PHONY: kirigami kirigami-package
