ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kitemviews.mk — kf6-itemviews for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kitemviews
KITEMVIEWS_VERSION = $(KF6_VERSION)
DEB_KITEMVIEWS_V ?= $(KITEMVIEWS_VERSION)

kitemviews-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kitemviews))
	$(call EXTRACT_TAR,kitemviews-$(KF6_VERSION).tar.xz,kitemviews-$(KF6_VERSION),kitemviews)
	$(call QT6_WRITE_IOSEXEC_FIXUP)

ifneq ($(wildcard $(BUILD_WORK)/kitemviews/.build_complete),)
kitemviews:
	@echo "Using previously built kitemviews."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kitemviews: kitemviews-setup
	mkdir -p $(BUILD_WORK)/kitemviews/build
	cd $(BUILD_WORK)/kitemviews/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kitemviews/build
	+DESTDIR="$(BUILD_STAGE)/kitemviews" ninja -C $(BUILD_WORK)/kitemviews/build install
	$(call AFTER_BUILD,copy)
endif

kitemviews-package: kitemviews-stage
	rm -rf $(BUILD_DIST)/kf6-itemviews $(BUILD_DIST)/kf6-itemviews-dev
	$(call KF6_COPY_RUNTIME,kitemviews,kf6-itemviews)
	$(call KF6_COPY_DEV,kitemviews,kf6-itemviews)
	$(call SIGN,kf6-itemviews,general.xml)
	$(call SIGN,kf6-itemviews-dev,general.xml)
	$(call PACK,kf6-itemviews,DEB_KITEMVIEWS_V)
	$(call PACK,kf6-itemviews-dev,DEB_KITEMVIEWS_V)
	rm -rf $(BUILD_DIST)/kf6-itemviews $(BUILD_DIST)/kf6-itemviews-dev

.PHONY: kitemviews kitemviews-package
