ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kitemmodels.mk — kf6-itemmodels for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Required directly by plasma-nano. QML bindings enabled because
# qt6-declarative is staged (optional dep auto-detected).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kitemmodels
KITEMMODELS_VERSION = $(KF6_VERSION)
DEB_KITEMMODELS_V ?= $(KITEMMODELS_VERSION)

kitemmodels-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kitemmodels))
	$(call EXTRACT_TAR,kitemmodels-$(KF6_VERSION).tar.xz,kitemmodels-$(KF6_VERSION),kitemmodels)
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kitemmodels/.build_complete),)
kitemmodels:
	@echo "Using previously built kitemmodels."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kitemmodels: kitemmodels-setup
	mkdir -p $(BUILD_WORK)/kitemmodels/build
	cd $(BUILD_WORK)/kitemmodels/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kitemmodels/build
	+DESTDIR="$(BUILD_STAGE)/kitemmodels" ninja -C $(BUILD_WORK)/kitemmodels/build install
	$(call AFTER_BUILD,copy)
endif

kitemmodels-package: kitemmodels-stage
	rm -rf $(BUILD_DIST)/kf6-itemmodels $(BUILD_DIST)/kf6-itemmodels-dev
	$(call KF6_COPY_RUNTIME,kitemmodels,kf6-itemmodels)
	$(call KF6_COPY_DEV,kitemmodels,kf6-itemmodels)
	$(call SIGN,kf6-itemmodels,general.xml)
	$(call SIGN,kf6-itemmodels-dev,general.xml)
	$(call PACK,kf6-itemmodels,DEB_KITEMMODELS_V)
	$(call PACK,kf6-itemmodels-dev,DEB_KITEMMODELS_V)
	rm -rf $(BUILD_DIST)/kf6-itemmodels $(BUILD_DIST)/kf6-itemmodels-dev

.PHONY: kitemmodels kitemmodels-package
