ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kjobwidgets.mk — kf6-jobwidgets for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# The reason KNotifications is unavoidable: kjobwidgets REQUIREs it
# unconditionally and KIO REQUIREs kjobwidgets.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kjobwidgets
KJOBWIDGETS_VERSION = $(KF6_VERSION)
DEB_KJOBWIDGETS_V ?= $(KJOBWIDGETS_VERSION)

kjobwidgets-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kjobwidgets))
	$(call EXTRACT_TAR,kjobwidgets-$(KF6_VERSION).tar.xz,kjobwidgets-$(KF6_VERSION),kjobwidgets)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kjobwidgets/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kjobwidgets/.build_complete),)
kjobwidgets:
	@echo "Using previously built kjobwidgets."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kjobwidgets: kjobwidgets-setup
	mkdir -p $(BUILD_WORK)/kjobwidgets/build
	cd $(BUILD_WORK)/kjobwidgets/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kjobwidgets/build
	+DESTDIR="$(BUILD_STAGE)/kjobwidgets" ninja -C $(BUILD_WORK)/kjobwidgets/build install
	$(call AFTER_BUILD,copy)
endif

kjobwidgets-package: kjobwidgets-stage
	rm -rf $(BUILD_DIST)/kf6-jobwidgets $(BUILD_DIST)/kf6-jobwidgets-dev
	$(call KF6_COPY_RUNTIME,kjobwidgets,kf6-jobwidgets)
	$(call KF6_COPY_DEV,kjobwidgets,kf6-jobwidgets)
	$(call SIGN,kf6-jobwidgets,general.xml)
	$(call SIGN,kf6-jobwidgets-dev,general.xml)
	$(call PACK,kf6-jobwidgets,DEB_KJOBWIDGETS_V)
	$(call PACK,kf6-jobwidgets-dev,DEB_KJOBWIDGETS_V)
	rm -rf $(BUILD_DIST)/kf6-jobwidgets $(BUILD_DIST)/kf6-jobwidgets-dev

.PHONY: kjobwidgets kjobwidgets-package
