ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# knewstuff.mk — kf6-newstuff for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Workspace's component gate requires NewStuff, but first light does not need
# Kirigami2 UI polish or feed support, so both optional branches are disabled.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += knewstuff
KNEWSTUFF_VERSION = $(KF6_VERSION)
DEB_KNEWSTUFF_V ?= $(KNEWSTUFF_VERSION)+ios1

knewstuff-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,knewstuff))
	$(call EXTRACT_TAR,knewstuff-$(KF6_VERSION).tar.xz,knewstuff-$(KF6_VERSION),knewstuff)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/knewstuff/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/knewstuff/.build_complete),)
knewstuff:
	@echo "Using previously built knewstuff."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
knewstuff: knewstuff-setup
	mkdir -p $(BUILD_WORK)/knewstuff/build
	cd $(BUILD_WORK)/knewstuff/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DCMAKE_DISABLE_FIND_PACKAGE_KF6Kirigami2=TRUE \
		-DCMAKE_DISABLE_FIND_PACKAGE_KF6Syndication=TRUE
	+ninja -C $(BUILD_WORK)/knewstuff/build
	+DESTDIR="$(BUILD_STAGE)/knewstuff" ninja -C $(BUILD_WORK)/knewstuff/build install
	$(call AFTER_BUILD,copy)
endif

knewstuff-package: knewstuff-stage
	rm -rf $(BUILD_DIST)/kf6-newstuff $(BUILD_DIST)/kf6-newstuff-dev
	$(call KF6_COPY_RUNTIME,knewstuff,kf6-newstuff)
	$(call KF6_COPY_DEV,knewstuff,kf6-newstuff)
	$(call SIGN,kf6-newstuff,general.xml)
	$(call SIGN,kf6-newstuff-dev,general.xml)
	$(call PACK,kf6-newstuff,DEB_KNEWSTUFF_V)
	$(call PACK,kf6-newstuff-dev,DEB_KNEWSTUFF_V)
	rm -rf $(BUILD_DIST)/kf6-newstuff $(BUILD_DIST)/kf6-newstuff-dev

.PHONY: knewstuff knewstuff-package
