ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating overwrites
# hand edits (fold fixes back into the table).

SUBPROJECTS += knewstuff
KNEWSTUFF_VERSION = $(KF6_VERSION)
DEB_KNEWSTUFF_V ?= $(KNEWSTUFF_VERSION)+ios2

knewstuff-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,knewstuff))
	$(call EXTRACT_TAR,knewstuff-$(KF6_VERSION).tar.xz,knewstuff-$(KF6_VERSION),knewstuff)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/knewstuff/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/knewstuff/.build_complete),)
knewstuff:
	@echo "Using previously built knewstuff."
else
# Deps are pre-staged by build_base (mutter.mk precedent); build-kf6.sh enforces
# build order, not make prereqs.
knewstuff: knewstuff-setup
	mkdir -p $(BUILD_WORK)/knewstuff/build
	cd $(BUILD_WORK)/knewstuff/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DCMAKE_DISABLE_FIND_PACKAGE_KF6Kirigami2=TRUE \
		-DCMAKE_DISABLE_FIND_PACKAGE_KF6Syndication=TRUE
	# First light doesn't need Kirigami2 UI polish or feed support; Workspace's
	# component gate just requires NewStuff itself.
	+ninja -C $(BUILD_WORK)/knewstuff/build
	+DESTDIR="$(BUILD_STAGE)/knewstuff" ninja -C $(BUILD_WORK)/knewstuff/build install
	$(call AFTER_BUILD,copy)
endif

knewstuff-package: knewstuff-stage
	rm -rf $(BUILD_DIST)/kf6-newstuff $(BUILD_DIST)/kf6-newstuff-dev
	$(call KF6_COPY_RUNTIME,knewstuff,kf6-newstuff)
	$(call KF6_COPY_DEV,knewstuff,kf6-newstuff)
	# knewstuff-dialog6 helper isn't installed in this cut; drop its desktop entry
	# rather than ship a launcher pointing at a missing binary.
	rm -f $(BUILD_DIST)/kf6-newstuff/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/share/applications/org.kde.knewstuff-dialog6.desktop
	$(call SIGN,kf6-newstuff,general.xml)
	$(call SIGN,kf6-newstuff-dev,general.xml)
	$(call PACK,kf6-newstuff,DEB_KNEWSTUFF_V)
	$(call PACK,kf6-newstuff-dev,DEB_KNEWSTUFF_V)
	rm -rf $(BUILD_DIST)/kf6-newstuff $(BUILD_DIST)/kf6-newstuff-dev

.PHONY: knewstuff knewstuff-package
