ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# knotifyconfig.mk — kf6-notifyconfig for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# The source already treats Canberra/Phonon as optional after configure; this
# sed demotes the fallback Phonon lookup so sound-preview support can stay off
# without blocking Workspace configuration.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += knotifyconfig
KNOTIFYCONFIG_VERSION = $(KF6_VERSION)
DEB_KNOTIFYCONFIG_V ?= $(KNOTIFYCONFIG_VERSION)+ios1

knotifyconfig-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,knotifyconfig))
	$(call EXTRACT_TAR,knotifyconfig-$(KF6_VERSION).tar.xz,knotifyconfig-$(KF6_VERSION),knotifyconfig)
	sed -i 's/find_package(Phonon4Qt6 4\.6\.60 NO_MODULE REQUIRED)/find_package(Phonon4Qt6 4.6.60 NO_MODULE)/' $(BUILD_WORK)/knotifyconfig/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/knotifyconfig/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/knotifyconfig/.build_complete),)
knotifyconfig:
	@echo "Using previously built knotifyconfig."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
knotifyconfig: knotifyconfig-setup
	mkdir -p $(BUILD_WORK)/knotifyconfig/build
	cd $(BUILD_WORK)/knotifyconfig/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/knotifyconfig/build
	+DESTDIR="$(BUILD_STAGE)/knotifyconfig" ninja -C $(BUILD_WORK)/knotifyconfig/build install
	$(call AFTER_BUILD,copy)
endif

knotifyconfig-package: knotifyconfig-stage
	rm -rf $(BUILD_DIST)/kf6-notifyconfig $(BUILD_DIST)/kf6-notifyconfig-dev
	$(call KF6_COPY_RUNTIME,knotifyconfig,kf6-notifyconfig)
	$(call KF6_COPY_DEV,knotifyconfig,kf6-notifyconfig)
	$(call SIGN,kf6-notifyconfig,general.xml)
	$(call SIGN,kf6-notifyconfig-dev,general.xml)
	$(call PACK,kf6-notifyconfig,DEB_KNOTIFYCONFIG_V)
	$(call PACK,kf6-notifyconfig-dev,DEB_KNOTIFYCONFIG_V)
	rm -rf $(BUILD_DIST)/kf6-notifyconfig $(BUILD_DIST)/kf6-notifyconfig-dev

.PHONY: knotifyconfig knotifyconfig-package
