ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# knotifications.mk — kf6-notifications for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Two audited patches, applied in -setup: (1) Canberra demoted from REQUIRED;
# the code already guards on the target existing, and sound notifications are
# not worth a libcanberra+vorbis chain right now. (2) the freedesktop/DBus
# branch is forced; the APPLE branch selects the macOS NSUserNotification
# backend, which does not exist on iPhoneOS. Expect matching APPLE guards in
# src/CMakeLists.txt at phase 2 (same class of fix).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += knotifications
KNOTIFICATIONS_VERSION = $(KF6_VERSION)
DEB_KNOTIFICATIONS_V ?= $(KNOTIFICATIONS_VERSION)

knotifications-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,knotifications))
	$(call EXTRACT_TAR,knotifications-$(KF6_VERSION).tar.xz,knotifications-$(KF6_VERSION),knotifications)
	sed -i 's/find_package(Canberra REQUIRED)/find_package(Canberra)/' $(BUILD_WORK)/knotifications/CMakeLists.txt
	sed -i 's/if (NOT APPLE AND NOT ANDROID AND NOT WIN32 OR (WIN32 AND NOT WITH_SNORETOAST))/if (TRUE)/' $(BUILD_WORK)/knotifications/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)

ifneq ($(wildcard $(BUILD_WORK)/knotifications/.build_complete),)
knotifications:
	@echo "Using previously built knotifications."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
knotifications: knotifications-setup
	mkdir -p $(BUILD_WORK)/knotifications/build
	cd $(BUILD_WORK)/knotifications/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/knotifications/build
	+DESTDIR="$(BUILD_STAGE)/knotifications" ninja -C $(BUILD_WORK)/knotifications/build install
	$(call AFTER_BUILD,copy)
endif

knotifications-package: knotifications-stage
	rm -rf $(BUILD_DIST)/kf6-notifications $(BUILD_DIST)/kf6-notifications-dev
	$(call KF6_COPY_RUNTIME,knotifications,kf6-notifications)
	$(call KF6_COPY_DEV,knotifications,kf6-notifications)
	$(call SIGN,kf6-notifications,general.xml)
	$(call SIGN,kf6-notifications-dev,general.xml)
	$(call PACK,kf6-notifications,DEB_KNOTIFICATIONS_V)
	$(call PACK,kf6-notifications-dev,DEB_KNOTIFICATIONS_V)
	rm -rf $(BUILD_DIST)/kf6-notifications $(BUILD_DIST)/kf6-notifications-dev

.PHONY: knotifications knotifications-package
