ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating overwrites
# hand edits (fold fixes back into the table).

SUBPROJECTS += knotifications
KNOTIFICATIONS_VERSION = $(KF6_VERSION)
DEB_KNOTIFICATIONS_V ?= $(KNOTIFICATIONS_VERSION)+ios1

knotifications-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,knotifications))
	$(call EXTRACT_TAR,knotifications-$(KF6_VERSION).tar.xz,knotifications-$(KF6_VERSION),knotifications)
	# Canberra demoted from REQUIRED: the code already guards on the target existing,
	# and sound notifications aren't worth a libcanberra+vorbis chain here.
	sed -i 's/find_package(Canberra REQUIRED)/find_package(Canberra)/' $(BUILD_WORK)/knotifications/CMakeLists.txt
	# Force the freedesktop/DBus backend; the APPLE branch selects macOS
	# NSUserNotification, which doesn't exist on iPhoneOS.
	sed -i 's/if (NOT APPLE AND NOT ANDROID AND NOT WIN32 OR (WIN32 AND NOT WITH_SNORETOAST))/if (TRUE)/' $(BUILD_WORK)/knotifications/CMakeLists.txt
	# Drop the macOS-only NSUserNotificationCenter backend and its AppKit link line;
	# Qt for iOS never defines Q_OS_MACOS so this code path is unreachable anyway.
	sed -i '/notifybymacosnotificationcenter.mm/d' $(BUILD_WORK)/knotifications/src/CMakeLists.txt
	sed -i '/-framework AppKit/d' $(BUILD_WORK)/knotifications/src/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/knotifications/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/knotifications/.build_complete),)
knotifications:
	@echo "Using previously built knotifications."
else
# Deps are pre-staged by build_base (mutter.mk precedent); build-kf6.sh enforces
# build order, not make prereqs.
knotifications: knotifications-setup
	mkdir -p $(BUILD_WORK)/knotifications/build
	cd $(BUILD_WORK)/knotifications/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/knotifications/build
	+DESTDIR="$(BUILD_STAGE)/knotifications" ninja -C $(BUILD_WORK)/knotifications/build install
	$(call AFTER_BUILD,copy)
endif

knotifications-package: knotifications-stage
	rm -rf $(BUILD_DIST)/kf6-notifications $(BUILD_DIST)/kf6-notifications-dev
	$(call KF6_COPY_RUNTIME,knotifications,kf6-notifications)
	$(call KF6_COPY_DEV,knotifications,kf6-notifications)
	$(call SIGN,kf6-notifications,general.xml)
	$(call SIGN,kf6-notifications-dev,general.xml)
	$(call PACK,kf6-notifications,DEB_KNOTIFICATIONS_V)
	$(call PACK,kf6-notifications-dev,DEB_KNOTIFICATIONS_V)
	rm -rf $(BUILD_DIST)/kf6-notifications $(BUILD_DIST)/kf6-notifications-dev

.PHONY: knotifications knotifications-package
