ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kpackage.mk — kf6-package for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Host-tooling provider (kpackagetool6): plasma_install_package() runs it at
# build time in libplasma/plasma-nano/plasma-mobile, so stage 1 builds it
# natively (which is why host karchive/ki18n exist at all).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kpackage
KPACKAGE_VERSION = $(KF6_VERSION)
DEB_KPACKAGE_V ?= $(KPACKAGE_VERSION)

kpackage-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kpackage))
	$(call EXTRACT_TAR,kpackage-$(KF6_VERSION).tar.xz,kpackage-$(KF6_VERSION),kpackage)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kpackage/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kpackage/.build_complete),)
kpackage:
	@echo "Using previously built kpackage."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kpackage: kpackage-setup
	mkdir -p $(BUILD_WORK)/kpackage/build
	cd $(BUILD_WORK)/kpackage/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kpackage/build
	+DESTDIR="$(BUILD_STAGE)/kpackage" ninja -C $(BUILD_WORK)/kpackage/build install
	$(call AFTER_BUILD,copy)
endif

kpackage-package: kpackage-stage
	rm -rf $(BUILD_DIST)/kf6-package $(BUILD_DIST)/kf6-package-dev
	$(call KF6_COPY_RUNTIME,kpackage,kf6-package)
	$(call KF6_COPY_DEV,kpackage,kf6-package)
	$(call SIGN,kf6-package,general.xml)
	$(call SIGN,kf6-package-dev,general.xml)
	$(call PACK,kf6-package,DEB_KPACKAGE_V)
	$(call PACK,kf6-package-dev,DEB_KPACKAGE_V)
	rm -rf $(BUILD_DIST)/kf6-package $(BUILD_DIST)/kf6-package-dev

.PHONY: kpackage kpackage-package
