ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kparts.mk — kf6-parts for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kparts
KPARTS_VERSION = $(KF6_VERSION)
DEB_KPARTS_V ?= $(KPARTS_VERSION)+ios1

kparts-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kparts))
	$(call EXTRACT_TAR,kparts-$(KF6_VERSION).tar.xz,kparts-$(KF6_VERSION),kparts)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kparts/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kparts/.build_complete),)
kparts:
	@echo "Using previously built kparts."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kparts: kparts-setup
	mkdir -p $(BUILD_WORK)/kparts/build
	cd $(BUILD_WORK)/kparts/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kparts/build
	+DESTDIR="$(BUILD_STAGE)/kparts" ninja -C $(BUILD_WORK)/kparts/build install
	$(call AFTER_BUILD,copy)
endif

kparts-package: kparts-stage
	rm -rf $(BUILD_DIST)/kf6-parts $(BUILD_DIST)/kf6-parts-dev
	$(call KF6_COPY_RUNTIME,kparts,kf6-parts)
	$(call KF6_COPY_DEV,kparts,kf6-parts)
	$(call SIGN,kf6-parts,general.xml)
	$(call SIGN,kf6-parts-dev,general.xml)
	$(call PACK,kf6-parts,DEB_KPARTS_V)
	$(call PACK,kf6-parts-dev,DEB_KPARTS_V)
	rm -rf $(BUILD_DIST)/kf6-parts $(BUILD_DIST)/kf6-parts-dev

.PHONY: kparts kparts-package
