ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kpty.mk - KF6 Pty, the pseudo-terminal layer Konsole hard-requires.
#
# NOT generated by tools/gen-kf6-recipes.py (kpty is not in that TABLE). Hand-written
# in the generated shape; if kpty is ever folded into the generator TABLE, delete this
# file rather than letting the two diverge.
#
# iOS viability (checked against the staged cross SDK, linux-build/sdk/iPhoneOS.sdk):
#   - <util.h> is present and declares openpty()/forkpty()/login_tty(); _openpty and
#     _forkpty are exported from usr/lib/libSystem.B.tbd (iOS folds libutil into
#     libSystem, so libutil.tbd itself only carries the mount/pidfile helpers).
#     ConfigureChecks.cmake's check_function_exists(openpty openpty_in_libc) therefore
#     succeeds -> HAVE_OPENPTY=1, UTIL_LIBRARY stays empty, and kgrantpty is not built
#     (it is only added when NOT HAVE_OPENPTY), so there is no CLI-executable
#     MACOSX_BUNDLE landmine in this unit.
#   - grantpt/unlockpt/ptsname/posix_openpt/revoke are all in libSystem too, so the
#     non-openpty fallback would also have worked.
#   - What iOS does NOT have is <utmp.h> (only <utmpx.h>) and any utmp/wtmp database,
#     and neither login() nor logout() is exported from libSystem. kpty.cpp's
#     non-utempter branch includes <utmp.h> unconditionally, so the two session-record
#     entry points are the only thing that has to go. They are no-ops here: nothing on
#     the device reads utmp.

SUBPROJECTS += kpty
KPTY_VERSION = $(KF6_VERSION)
DEB_KPTY_V ?= $(KPTY_VERSION)+ios1

kpty-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kpty))
	$(call EXTRACT_TAR,kpty-$(KF6_VERSION).tar.xz,kpty-$(KF6_VERSION),kpty)
	bash $(BUILD_INFO)/kpty-ios-fixes.sh $(BUILD_WORK)/kpty
	perl -0777 -i -pe 's/\n#include <utmp\.h>\n/\n\/\/ ios-bringup-no-utmp: iPhoneOS SDK ships utmpx.h only\n#if !defined(__APPLE__)\n#include <utmp.h>\n#endif\n/s' $(BUILD_WORK)/kpty/src/kpty.cpp
	perl -0777 -i -pe 's/void KPty::login\(const char \*user, const char \*remotehost\)\n\{\n#ifdef UTEMPTER_PATH\n/void KPty::login(const char *user, const char *remotehost)\n{\n#if defined(__APPLE__) \/\/ ios-bringup-no-utmp\n    (void)user;\n    (void)remotehost;\n#elif defined(UTEMPTER_PATH)\n/s' $(BUILD_WORK)/kpty/src/kpty.cpp
	perl -0777 -i -pe 's/void KPty::logout\(\)\n\{\n#ifdef UTEMPTER_PATH\n/void KPty::logout()\n{\n#if defined(__APPLE__) \/\/ ios-bringup-no-utmp\n#elif defined(UTEMPTER_PATH)\n/s' $(BUILD_WORK)/kpty/src/kpty.cpp
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kpty/.build_complete),)
kpty:
	@echo "Using previously built kpty."
else
kpty: kpty-setup
	rm -rf $(BUILD_WORK)/kpty/build
	mkdir -p $(BUILD_WORK)/kpty/build
	cd $(BUILD_WORK)/kpty/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DBUILD_QCH=OFF \
		-DCMAKE_DISABLE_FIND_PACKAGE_UTEMPTER=TRUE
	+ninja -C $(BUILD_WORK)/kpty/build
	+DESTDIR="$(BUILD_STAGE)/kpty" ninja -C $(BUILD_WORK)/kpty/build install
	$(call AFTER_BUILD,copy)
endif

kpty-package: kpty-stage
	rm -rf $(BUILD_DIST)/kf6-pty $(BUILD_DIST)/kf6-pty-dev
	$(call KF6_COPY_RUNTIME,kpty,kf6-pty)
	$(call KF6_COPY_DEV,kpty,kf6-pty)
	$(call SIGN,kf6-pty,general.xml)
	$(call PACK,kf6-pty,DEB_KPTY_V)
	$(call PACK,kf6-pty-dev,DEB_KPTY_V)
	rm -rf $(BUILD_DIST)/kf6-pty $(BUILD_DIST)/kf6-pty-dev

.PHONY: kpty kpty-package
