ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# krunner.mk — kf6-runner for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# KF6ItemModels is optional upstream but staged in our base KF6 set; keep the
# runtime/control dependency explicit because Workspace runner plumbing uses it.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += krunner
KRUNNER_VERSION = $(KF6_VERSION)
DEB_KRUNNER_V ?= $(KRUNNER_VERSION)+ios1

krunner-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,krunner))
	$(call EXTRACT_TAR,krunner-$(KF6_VERSION).tar.xz,krunner-$(KF6_VERSION),krunner)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/krunner/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/krunner/.build_complete),)
krunner:
	@echo "Using previously built krunner."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
krunner: krunner-setup
	mkdir -p $(BUILD_WORK)/krunner/build
	cd $(BUILD_WORK)/krunner/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/krunner/build
	+DESTDIR="$(BUILD_STAGE)/krunner" ninja -C $(BUILD_WORK)/krunner/build install
	$(call AFTER_BUILD,copy)
endif

krunner-package: krunner-stage
	rm -rf $(BUILD_DIST)/kf6-runner $(BUILD_DIST)/kf6-runner-dev
	$(call KF6_COPY_RUNTIME,krunner,kf6-runner)
	$(call KF6_COPY_DEV,krunner,kf6-runner)
	$(call SIGN,kf6-runner,general.xml)
	$(call SIGN,kf6-runner-dev,general.xml)
	$(call PACK,kf6-runner,DEB_KRUNNER_V)
	$(call PACK,kf6-runner-dev,DEB_KRUNNER_V)
	rm -rf $(BUILD_DIST)/kf6-runner $(BUILD_DIST)/kf6-runner-dev

.PHONY: krunner krunner-package
