ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kservice.mk — kf6-service for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# bison/flex on the build host (trader query parser). Ships kbuildsycoca6 in
# the runtime deb; the sycoca cache builds on-device at first login.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kservice
KSERVICE_VERSION = $(KF6_VERSION)
DEB_KSERVICE_V ?= $(KSERVICE_VERSION)+ios1

kservice-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kservice))
	$(call EXTRACT_TAR,kservice-$(KF6_VERSION).tar.xz,kservice-$(KF6_VERSION),kservice)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kservice/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kservice/.build_complete),)
kservice:
	@echo "Using previously built kservice."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kservice: kservice-setup
	mkdir -p $(BUILD_WORK)/kservice/build
	cd $(BUILD_WORK)/kservice/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kservice/build
	+DESTDIR="$(BUILD_STAGE)/kservice" ninja -C $(BUILD_WORK)/kservice/build install
	$(call AFTER_BUILD,copy)
endif

kservice-package: kservice-stage
	rm -rf $(BUILD_DIST)/kf6-service $(BUILD_DIST)/kf6-service-dev
	$(call KF6_COPY_RUNTIME,kservice,kf6-service)
	$(call KF6_COPY_DEV,kservice,kf6-service)
	$(call SIGN,kf6-service,general.xml)
	$(call SIGN,kf6-service-dev,general.xml)
	$(call PACK,kf6-service,DEB_KSERVICE_V)
	$(call PACK,kf6-service-dev,DEB_KSERVICE_V)
	rm -rf $(BUILD_DIST)/kf6-service $(BUILD_DIST)/kf6-service-dev

.PHONY: kservice kservice-package
