ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating overwrites
# hand edits (fold fixes back into the table).

SUBPROJECTS += kstatusnotifieritem
KSTATUSNOTIFIERITEM_VERSION = $(KF6_VERSION)
DEB_KSTATUSNOTIFIERITEM_V ?= $(KSTATUSNOTIFIERITEM_VERSION)+ios1

kstatusnotifieritem-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kstatusnotifieritem))
	$(call EXTRACT_TAR,kstatusnotifieritem-$(KF6_VERSION).tar.xz,kstatusnotifieritem-$(KF6_VERSION),kstatusnotifieritem)
	# macutils.mm imports AppKit and is macOS-only; force this block off for iOS.
	sed -i 's/^if(APPLE)$/if(FALSE) # iOS: no AppKit/' $(BUILD_WORK)/kstatusnotifieritem/src/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kstatusnotifieritem/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kstatusnotifieritem/.build_complete),)
kstatusnotifieritem:
	@echo "Using previously built kstatusnotifieritem."
else
# Deps are pre-staged by build_base (mutter.mk precedent); build-kf6.sh enforces
# build order, not make prereqs.
kstatusnotifieritem: kstatusnotifieritem-setup
	mkdir -p $(BUILD_WORK)/kstatusnotifieritem/build
	cd $(BUILD_WORK)/kstatusnotifieritem/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DWITHOUT_X11=ON # keeps only the DBus/freedesktop status notifier path
	+ninja -C $(BUILD_WORK)/kstatusnotifieritem/build
	+DESTDIR="$(BUILD_STAGE)/kstatusnotifieritem" ninja -C $(BUILD_WORK)/kstatusnotifieritem/build install
	$(call AFTER_BUILD,copy)
endif

kstatusnotifieritem-package: kstatusnotifieritem-stage
	rm -rf $(BUILD_DIST)/kf6-statusnotifieritem $(BUILD_DIST)/kf6-statusnotifieritem-dev
	$(call KF6_COPY_RUNTIME,kstatusnotifieritem,kf6-statusnotifieritem)
	$(call KF6_COPY_DEV,kstatusnotifieritem,kf6-statusnotifieritem)
	$(call SIGN,kf6-statusnotifieritem,general.xml)
	$(call SIGN,kf6-statusnotifieritem-dev,general.xml)
	$(call PACK,kf6-statusnotifieritem,DEB_KSTATUSNOTIFIERITEM_V)
	$(call PACK,kf6-statusnotifieritem-dev,DEB_KSTATUSNOTIFIERITEM_V)
	rm -rf $(BUILD_DIST)/kf6-statusnotifieritem $(BUILD_DIST)/kf6-statusnotifieritem-dev

.PHONY: kstatusnotifieritem kstatusnotifieritem-package
