ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# ksvg.mk — kf6-svg for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Direct kwin requirement (KF6::Svg). The KirigamiPlatform dep is why kirigami
# sits in wave 1.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += ksvg
KSVG_VERSION = $(KF6_VERSION)
DEB_KSVG_V ?= $(KSVG_VERSION)

ksvg-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,ksvg))
	$(call EXTRACT_TAR,ksvg-$(KF6_VERSION).tar.xz,ksvg-$(KF6_VERSION),ksvg)
	$(call QT6_WRITE_IOSEXEC_FIXUP)

ifneq ($(wildcard $(BUILD_WORK)/ksvg/.build_complete),)
ksvg:
	@echo "Using previously built ksvg."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
ksvg: ksvg-setup
	mkdir -p $(BUILD_WORK)/ksvg/build
	cd $(BUILD_WORK)/ksvg/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/ksvg/build
	+DESTDIR="$(BUILD_STAGE)/ksvg" ninja -C $(BUILD_WORK)/ksvg/build install
	$(call AFTER_BUILD,copy)
endif

ksvg-package: ksvg-stage
	rm -rf $(BUILD_DIST)/kf6-svg $(BUILD_DIST)/kf6-svg-dev
	$(call KF6_COPY_RUNTIME,ksvg,kf6-svg)
	$(call KF6_COPY_DEV,ksvg,kf6-svg)
	$(call SIGN,kf6-svg,general.xml)
	$(call SIGN,kf6-svg-dev,general.xml)
	$(call PACK,kf6-svg,DEB_KSVG_V)
	$(call PACK,kf6-svg-dev,DEB_KSVG_V)
	rm -rf $(BUILD_DIST)/kf6-svg $(BUILD_DIST)/kf6-svg-dev

.PHONY: ksvg ksvg-package
