ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# ktextwidgets.mk — kf6-textwidgets for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# WITH_TEXT_TO_SPEECH=OFF is load-bearing: ON would pull Qt6TextToSpeech and
# with it the whole qtspeech module. The audit found this switch; without it
# the Qt module set would grow by one for a feature nobody asked for.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += ktextwidgets
KTEXTWIDGETS_VERSION = $(KF6_VERSION)
DEB_KTEXTWIDGETS_V ?= $(KTEXTWIDGETS_VERSION)

ktextwidgets-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,ktextwidgets))
	$(call EXTRACT_TAR,ktextwidgets-$(KF6_VERSION).tar.xz,ktextwidgets-$(KF6_VERSION),ktextwidgets)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/ktextwidgets/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/ktextwidgets/.build_complete),)
ktextwidgets:
	@echo "Using previously built ktextwidgets."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
ktextwidgets: ktextwidgets-setup
	mkdir -p $(BUILD_WORK)/ktextwidgets/build
	cd $(BUILD_WORK)/ktextwidgets/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DWITH_TEXT_TO_SPEECH=OFF
	+ninja -C $(BUILD_WORK)/ktextwidgets/build
	+DESTDIR="$(BUILD_STAGE)/ktextwidgets" ninja -C $(BUILD_WORK)/ktextwidgets/build install
	$(call AFTER_BUILD,copy)
endif

ktextwidgets-package: ktextwidgets-stage
	rm -rf $(BUILD_DIST)/kf6-textwidgets $(BUILD_DIST)/kf6-textwidgets-dev
	$(call KF6_COPY_RUNTIME,ktextwidgets,kf6-textwidgets)
	$(call KF6_COPY_DEV,ktextwidgets,kf6-textwidgets)
	$(call SIGN,kf6-textwidgets,general.xml)
	$(call SIGN,kf6-textwidgets-dev,general.xml)
	$(call PACK,kf6-textwidgets,DEB_KTEXTWIDGETS_V)
	$(call PACK,kf6-textwidgets-dev,DEB_KTEXTWIDGETS_V)
	rm -rf $(BUILD_DIST)/kf6-textwidgets $(BUILD_DIST)/kf6-textwidgets-dev

.PHONY: ktextwidgets ktextwidgets-package
