ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating overwrites
# hand edits (fold fixes back into the table).

SUBPROJECTS += ktextwidgets
KTEXTWIDGETS_VERSION = $(KF6_VERSION)
DEB_KTEXTWIDGETS_V ?= $(KTEXTWIDGETS_VERSION)+ios1

ktextwidgets-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,ktextwidgets))
	$(call EXTRACT_TAR,ktextwidgets-$(KF6_VERSION).tar.xz,ktextwidgets-$(KF6_VERSION),ktextwidgets)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/ktextwidgets/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/ktextwidgets/.build_complete),)
ktextwidgets:
	@echo "Using previously built ktextwidgets."
else
# Deps are pre-staged by build_base (mutter.mk precedent); build-kf6.sh enforces
# build order, not make prereqs.
ktextwidgets: ktextwidgets-setup
	mkdir -p $(BUILD_WORK)/ktextwidgets/build
	cd $(BUILD_WORK)/ktextwidgets/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DWITH_TEXT_TO_SPEECH=OFF # ON pulls in the whole Qt6TextToSpeech module for no reason
	+ninja -C $(BUILD_WORK)/ktextwidgets/build
	+DESTDIR="$(BUILD_STAGE)/ktextwidgets" ninja -C $(BUILD_WORK)/ktextwidgets/build install
	$(call AFTER_BUILD,copy)
endif

ktextwidgets-package: ktextwidgets-stage
	rm -rf $(BUILD_DIST)/kf6-textwidgets $(BUILD_DIST)/kf6-textwidgets-dev
	$(call KF6_COPY_RUNTIME,ktextwidgets,kf6-textwidgets)
	$(call KF6_COPY_DEV,ktextwidgets,kf6-textwidgets)
	$(call SIGN,kf6-textwidgets,general.xml)
	$(call SIGN,kf6-textwidgets-dev,general.xml)
	$(call PACK,kf6-textwidgets,DEB_KTEXTWIDGETS_V)
	$(call PACK,kf6-textwidgets-dev,DEB_KTEXTWIDGETS_V)
	rm -rf $(BUILD_DIST)/kf6-textwidgets $(BUILD_DIST)/kf6-textwidgets-dev

.PHONY: ktextwidgets ktextwidgets-package
