ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kunitconversion.mk — kf6-unitconversion for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kunitconversion
KUNITCONVERSION_VERSION = $(KF6_VERSION)
DEB_KUNITCONVERSION_V ?= $(KUNITCONVERSION_VERSION)+ios1

kunitconversion-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kunitconversion))
	$(call EXTRACT_TAR,kunitconversion-$(KF6_VERSION).tar.xz,kunitconversion-$(KF6_VERSION),kunitconversion)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kunitconversion/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kunitconversion/.build_complete),)
kunitconversion:
	@echo "Using previously built kunitconversion."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kunitconversion: kunitconversion-setup
	mkdir -p $(BUILD_WORK)/kunitconversion/build
	cd $(BUILD_WORK)/kunitconversion/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kunitconversion/build
	+DESTDIR="$(BUILD_STAGE)/kunitconversion" ninja -C $(BUILD_WORK)/kunitconversion/build install
	$(call AFTER_BUILD,copy)
endif

kunitconversion-package: kunitconversion-stage
	rm -rf $(BUILD_DIST)/kf6-unitconversion $(BUILD_DIST)/kf6-unitconversion-dev
	$(call KF6_COPY_RUNTIME,kunitconversion,kf6-unitconversion)
	$(call KF6_COPY_DEV,kunitconversion,kf6-unitconversion)
	$(call SIGN,kf6-unitconversion,general.xml)
	$(call SIGN,kf6-unitconversion-dev,general.xml)
	$(call PACK,kf6-unitconversion,DEB_KUNITCONVERSION_V)
	$(call PACK,kf6-unitconversion-dev,DEB_KUNITCONVERSION_V)
	rm -rf $(BUILD_DIST)/kf6-unitconversion $(BUILD_DIST)/kf6-unitconversion-dev

.PHONY: kunitconversion kunitconversion-package
