ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kwallet.mk — kf6-wallet for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# API-only first-light build. Disabling kwalletd/query avoids QCA, Gcrypt,
# GpgME and daemon productization while still satisfying Workspace's Wallet
# CMake component.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kwallet
KWALLET_VERSION = $(KF6_VERSION)
DEB_KWALLET_V ?= $(KWALLET_VERSION)+ios1

kwallet-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kwallet))
	$(call EXTRACT_TAR,kwallet-$(KF6_VERSION).tar.xz,kwallet-$(KF6_VERSION),kwallet)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kwallet/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kwallet/.build_complete),)
kwallet:
	@echo "Using previously built kwallet."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kwallet: kwallet-setup
	mkdir -p $(BUILD_WORK)/kwallet/build
	cd $(BUILD_WORK)/kwallet/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DBUILD_KWALLETD=OFF \
		-DBUILD_KWALLET_QUERY=OFF \
		-DCMAKE_DISABLE_FIND_PACKAGE_KF6DocTools=TRUE
	+ninja -C $(BUILD_WORK)/kwallet/build
	+DESTDIR="$(BUILD_STAGE)/kwallet" ninja -C $(BUILD_WORK)/kwallet/build install
	$(call AFTER_BUILD,copy)
endif

kwallet-package: kwallet-stage
	rm -rf $(BUILD_DIST)/kf6-wallet $(BUILD_DIST)/kf6-wallet-dev
	$(call KF6_COPY_RUNTIME,kwallet,kf6-wallet)
	$(call KF6_COPY_DEV,kwallet,kf6-wallet)
	$(call SIGN,kf6-wallet,general.xml)
	$(call SIGN,kf6-wallet-dev,general.xml)
	$(call PACK,kf6-wallet,DEB_KWALLET_V)
	$(call PACK,kf6-wallet-dev,DEB_KWALLET_V)
	rm -rf $(BUILD_DIST)/kf6-wallet $(BUILD_DIST)/kf6-wallet-dev

.PHONY: kwallet kwallet-package
