ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kwayland.mk — kwayland for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Links EGL directly (audited REQUIRED): headers/libs resolve from the staged
# ANGLE chain in build_base, on-device from the angle deb. No KF deps at all,
# so it builds in wave 1 alongside the Qt-only frameworks.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kwayland
KWAYLAND_VERSION = $(PLASMA_VERSION)
DEB_KWAYLAND_V ?= $(KWAYLAND_VERSION)+ios1

kwayland-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call PLASMA_URL,kwayland))
	$(call EXTRACT_TAR,kwayland-$(PLASMA_VERSION).tar.xz,kwayland-$(PLASMA_VERSION),kwayland)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kwayland/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kwayland/.build_complete),)
kwayland:
	@echo "Using previously built kwayland."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kwayland: kwayland-setup
	mkdir -p $(BUILD_WORK)/kwayland/build
	cd $(BUILD_WORK)/kwayland/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kwayland/build
	+DESTDIR="$(BUILD_STAGE)/kwayland" ninja -C $(BUILD_WORK)/kwayland/build install
	$(call AFTER_BUILD,copy)
endif

kwayland-package: kwayland-stage
	rm -rf $(BUILD_DIST)/kwayland $(BUILD_DIST)/kwayland-dev
	$(call KF6_COPY_RUNTIME,kwayland,kwayland)
	$(call KF6_COPY_DEV,kwayland,kwayland)
	$(call SIGN,kwayland,general.xml)
	$(call SIGN,kwayland-dev,general.xml)
	$(call PACK,kwayland,DEB_KWAYLAND_V)
	$(call PACK,kwayland-dev,DEB_KWAYLAND_V)
	rm -rf $(BUILD_DIST)/kwayland $(BUILD_DIST)/kwayland-dev

.PHONY: kwayland kwayland-package
