ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Links EGL directly: headers/libs resolve from the staged ANGLE chain in build_base,
# on-device from the angle deb.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating overwrites
# hand edits (fold fixes back into the table).

SUBPROJECTS += kwayland
KWAYLAND_VERSION = $(PLASMA_VERSION)
DEB_KWAYLAND_V ?= $(KWAYLAND_VERSION)+ios1

kwayland-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call PLASMA_URL,kwayland))
	$(call EXTRACT_TAR,kwayland-$(PLASMA_VERSION).tar.xz,kwayland-$(PLASMA_VERSION),kwayland)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kwayland/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kwayland/.build_complete),)
kwayland:
	@echo "Using previously built kwayland."
else
# Deps are pre-staged by build_base (mutter.mk precedent); build-kf6.sh enforces
# build order, not make prereqs.
kwayland: kwayland-setup
	mkdir -p $(BUILD_WORK)/kwayland/build
	cd $(BUILD_WORK)/kwayland/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kwayland/build
	+DESTDIR="$(BUILD_STAGE)/kwayland" ninja -C $(BUILD_WORK)/kwayland/build install
	$(call AFTER_BUILD,copy)
endif

kwayland-package: kwayland-stage
	rm -rf $(BUILD_DIST)/kwayland $(BUILD_DIST)/kwayland-dev
	$(call KF6_COPY_RUNTIME,kwayland,kwayland)
	$(call KF6_COPY_DEV,kwayland,kwayland)
	$(call SIGN,kwayland,general.xml)
	$(call SIGN,kwayland-dev,general.xml)
	$(call PACK,kwayland,DEB_KWAYLAND_V)
	$(call PACK,kwayland-dev,DEB_KWAYLAND_V)
	rm -rf $(BUILD_DIST)/kwayland $(BUILD_DIST)/kwayland-dev

.PHONY: kwayland kwayland-package
