ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating overwrites
# hand edits (fold fixes back into the table).

SUBPROJECTS += kwidgetsaddons
KWIDGETSADDONS_VERSION = $(KF6_VERSION)
DEB_KWIDGETSADDONS_V ?= $(KWIDGETSADDONS_VERSION)+ios1

kwidgetsaddons-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kwidgetsaddons))
	$(call EXTRACT_TAR,kwidgetsaddons-$(KF6_VERSION).tar.xz,kwidgetsaddons-$(KF6_VERSION),kwidgetsaddons)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kwidgetsaddons/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kwidgetsaddons/.build_complete),)
kwidgetsaddons:
	@echo "Using previously built kwidgetsaddons."
else
# Deps are pre-staged by build_base (mutter.mk precedent); build-kf6.sh enforces
# build order, not make prereqs.
kwidgetsaddons: kwidgetsaddons-setup
	mkdir -p $(BUILD_WORK)/kwidgetsaddons/build
	cd $(BUILD_WORK)/kwidgetsaddons/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kwidgetsaddons/build
	+DESTDIR="$(BUILD_STAGE)/kwidgetsaddons" ninja -C $(BUILD_WORK)/kwidgetsaddons/build install
	$(call AFTER_BUILD,copy)
endif

kwidgetsaddons-package: kwidgetsaddons-stage
	rm -rf $(BUILD_DIST)/kf6-widgetsaddons $(BUILD_DIST)/kf6-widgetsaddons-dev
	$(call KF6_COPY_RUNTIME,kwidgetsaddons,kf6-widgetsaddons)
	$(call KF6_COPY_DEV,kwidgetsaddons,kf6-widgetsaddons)
	$(call SIGN,kf6-widgetsaddons,general.xml)
	$(call SIGN,kf6-widgetsaddons-dev,general.xml)
	$(call PACK,kf6-widgetsaddons,DEB_KWIDGETSADDONS_V)
	$(call PACK,kf6-widgetsaddons-dev,DEB_KWIDGETSADDONS_V)
	rm -rf $(BUILD_DIST)/kf6-widgetsaddons $(BUILD_DIST)/kf6-widgetsaddons-dev

.PHONY: kwidgetsaddons kwidgetsaddons-package
