ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# The APPLE guard hard-sets KWINDOWSYSTEM_WAYLAND OFF via plain set() (beats
# the -D cache flag), so the sed below strips just that line to keep wayland on.
# Wayland half is consumed by kwin, plasma-nano, libplasma.
# Generated by tools/gen-kf6-recipes.py — hand edits are lost on regen, fold
# fixes back into the K0 audit table.

SUBPROJECTS += kwindowsystem
KWINDOWSYSTEM_VERSION = $(KF6_VERSION)
DEB_KWINDOWSYSTEM_V ?= $(KWINDOWSYSTEM_VERSION)+ios1

kwindowsystem-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kwindowsystem))
	$(call EXTRACT_TAR,kwindowsystem-$(KF6_VERSION).tar.xz,kwindowsystem-$(KF6_VERSION),kwindowsystem)
	sed -i '/set(KWINDOWSYSTEM_WAYLAND OFF)/d' $(BUILD_WORK)/kwindowsystem/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kwindowsystem/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kwindowsystem/.build_complete),)
kwindowsystem:
	@echo "Using previously built kwindowsystem."
else
# No make-level prereqs: deps are staged by build_base; build-kf6.sh enforces wave order.
kwindowsystem: kwindowsystem-setup
	mkdir -p $(BUILD_WORK)/kwindowsystem/build
	cd $(BUILD_WORK)/kwindowsystem/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS) \
		-DKWINDOWSYSTEM_X11=OFF \
		-DKWINDOWSYSTEM_WAYLAND=ON
	+ninja -C $(BUILD_WORK)/kwindowsystem/build
	+DESTDIR="$(BUILD_STAGE)/kwindowsystem" ninja -C $(BUILD_WORK)/kwindowsystem/build install
	$(call AFTER_BUILD,copy)
endif

kwindowsystem-package: kwindowsystem-stage
	rm -rf $(BUILD_DIST)/kf6-windowsystem $(BUILD_DIST)/kf6-windowsystem-dev
	$(call KF6_COPY_RUNTIME,kwindowsystem,kf6-windowsystem)
	$(call KF6_COPY_DEV,kwindowsystem,kf6-windowsystem)
	$(call SIGN,kf6-windowsystem,general.xml)
	$(call SIGN,kf6-windowsystem-dev,general.xml)
	$(call PACK,kf6-windowsystem,DEB_KWINDOWSYSTEM_V)
	$(call PACK,kf6-windowsystem-dev,DEB_KWINDOWSYSTEM_V)
	rm -rf $(BUILD_DIST)/kf6-windowsystem $(BUILD_DIST)/kf6-windowsystem-dev

.PHONY: kwindowsystem kwindowsystem-package
