ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# kxmlgui.mk — kf6-xmlgui for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# REQUIREs Qt6PrintSupport (audited, unconditional): qtbase round 1 built
# printsupport OFF, so the round-2 rebuild (plan Q3) must flip
# FEATURE_printsupport=ON alongside dbus/xkbcommon. cups stays OFF.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += kxmlgui
KXMLGUI_VERSION = $(KF6_VERSION)
DEB_KXMLGUI_V ?= $(KXMLGUI_VERSION)

kxmlgui-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kxmlgui))
	$(call EXTRACT_TAR,kxmlgui-$(KF6_VERSION).tar.xz,kxmlgui-$(KF6_VERSION),kxmlgui)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kxmlgui/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kxmlgui/.build_complete),)
kxmlgui:
	@echo "Using previously built kxmlgui."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
kxmlgui: kxmlgui-setup
	mkdir -p $(BUILD_WORK)/kxmlgui/build
	cd $(BUILD_WORK)/kxmlgui/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kxmlgui/build
	+DESTDIR="$(BUILD_STAGE)/kxmlgui" ninja -C $(BUILD_WORK)/kxmlgui/build install
	$(call AFTER_BUILD,copy)
endif

kxmlgui-package: kxmlgui-stage
	rm -rf $(BUILD_DIST)/kf6-xmlgui $(BUILD_DIST)/kf6-xmlgui-dev
	$(call KF6_COPY_RUNTIME,kxmlgui,kf6-xmlgui)
	$(call KF6_COPY_DEV,kxmlgui,kf6-xmlgui)
	$(call SIGN,kf6-xmlgui,general.xml)
	$(call SIGN,kf6-xmlgui-dev,general.xml)
	$(call PACK,kf6-xmlgui,DEB_KXMLGUI_V)
	$(call PACK,kf6-xmlgui-dev,DEB_KXMLGUI_V)
	rm -rf $(BUILD_DIST)/kf6-xmlgui $(BUILD_DIST)/kf6-xmlgui-dev

.PHONY: kxmlgui kxmlgui-package
