ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Requires Qt6PrintSupport. qtbase round 1 builds with printsupport OFF, so the
# round-2 rebuild must flip FEATURE_printsupport=ON (with dbus/xkbcommon); cups stays OFF.
# Generated by tools/gen-kf6-recipes.py — hand edits are lost on regen, fold
# fixes back into the K0 audit table.

SUBPROJECTS += kxmlgui
KXMLGUI_VERSION = $(KF6_VERSION)
DEB_KXMLGUI_V ?= $(KXMLGUI_VERSION)+ios1

kxmlgui-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,kxmlgui))
	$(call EXTRACT_TAR,kxmlgui-$(KF6_VERSION).tar.xz,kxmlgui-$(KF6_VERSION),kxmlgui)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/kxmlgui/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/kxmlgui/.build_complete),)
kxmlgui:
	@echo "Using previously built kxmlgui."
else
# No make-level prereqs: deps are staged by build_base; build-kf6.sh enforces wave order.
kxmlgui: kxmlgui-setup
	mkdir -p $(BUILD_WORK)/kxmlgui/build
	cd $(BUILD_WORK)/kxmlgui/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/kxmlgui/build
	+DESTDIR="$(BUILD_STAGE)/kxmlgui" ninja -C $(BUILD_WORK)/kxmlgui/build install
	$(call AFTER_BUILD,copy)
endif

kxmlgui-package: kxmlgui-stage
	rm -rf $(BUILD_DIST)/kf6-xmlgui $(BUILD_DIST)/kf6-xmlgui-dev
	$(call KF6_COPY_RUNTIME,kxmlgui,kf6-xmlgui)
	$(call KF6_COPY_DEV,kxmlgui,kf6-xmlgui)
	$(call SIGN,kf6-xmlgui,general.xml)
	$(call SIGN,kf6-xmlgui-dev,general.xml)
	$(call PACK,kf6-xmlgui,DEB_KXMLGUI_V)
	$(call PACK,kf6-xmlgui-dev,DEB_KXMLGUI_V)
	rm -rf $(BUILD_DIST)/kf6-xmlgui $(BUILD_DIST)/kf6-xmlgui-dev

.PHONY: kxmlgui kxmlgui-package
