ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# layer-shell-qt.mk — layer-shell-qt for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Not a kwin dep; plasma-workspace panels sit on it (and iosc already speaks
# zwlr_layer_shell_v1 v4, so nested-kwin panels can bypass kwin entirely).
# Needs the host wayland-scanner (build-kf6.sh apt gate, same as qtwayland).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += layer-shell-qt
LAYERSHELLQT_VERSION = $(PLASMA_VERSION)
DEB_LAYERSHELLQT_V ?= $(LAYERSHELLQT_VERSION)+ios1

layer-shell-qt-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call PLASMA_URL,layer-shell-qt))
	$(call EXTRACT_TAR,layer-shell-qt-$(PLASMA_VERSION).tar.xz,layer-shell-qt-$(PLASMA_VERSION),layer-shell-qt)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/layer-shell-qt/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/layer-shell-qt/.build_complete),)
layer-shell-qt:
	@echo "Using previously built layer-shell-qt."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
layer-shell-qt: layer-shell-qt-setup
	mkdir -p $(BUILD_WORK)/layer-shell-qt/build
	cd $(BUILD_WORK)/layer-shell-qt/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/layer-shell-qt/build
	+DESTDIR="$(BUILD_STAGE)/layer-shell-qt" ninja -C $(BUILD_WORK)/layer-shell-qt/build install
	$(call AFTER_BUILD,copy)
endif

layer-shell-qt-package: layer-shell-qt-stage
	rm -rf $(BUILD_DIST)/layer-shell-qt $(BUILD_DIST)/layer-shell-qt-dev
	$(call KF6_COPY_RUNTIME,layer-shell-qt,layer-shell-qt)
	$(call KF6_COPY_DEV,layer-shell-qt,layer-shell-qt)
	$(call SIGN,layer-shell-qt,general.xml)
	$(call SIGN,layer-shell-qt-dev,general.xml)
	$(call PACK,layer-shell-qt,DEB_LAYERSHELLQT_V)
	$(call PACK,layer-shell-qt-dev,DEB_LAYERSHELLQT_V)
	rm -rf $(BUILD_DIST)/layer-shell-qt $(BUILD_DIST)/layer-shell-qt-dev

.PHONY: layer-shell-qt layer-shell-qt-package
