ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# Qt Core+DBus only in Plasma 6 (boost dependency dropped); libplasma requires it.
# kactivitymanagerd (the daemon) is a separate hand-maintained recipe
# (kactivitymanagerd.mk), built via the Workspace-layer driver, not this table.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits — fold changes back into the table.

SUBPROJECTS += plasma-activities
PLASMAACTIVITIES_VERSION = $(PLASMA_VERSION)
DEB_PLASMAACTIVITIES_V ?= $(PLASMAACTIVITIES_VERSION)+ios1

plasma-activities-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call PLASMA_URL,plasma-activities))
	$(call EXTRACT_TAR,plasma-activities-$(PLASMA_VERSION).tar.xz,plasma-activities-$(PLASMA_VERSION),plasma-activities)
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/plasma-activities/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/plasma-activities/.build_complete),)
plasma-activities:
	@echo "Using previously built plasma-activities."
else
# No make-level prereqs; deps come pre-staged from build_base (mutter.mk
# precedent) and build-kf6.sh runs targets in audit wave order.
plasma-activities: plasma-activities-setup
	mkdir -p $(BUILD_WORK)/plasma-activities/build
	cd $(BUILD_WORK)/plasma-activities/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/plasma-activities/build
	+DESTDIR="$(BUILD_STAGE)/plasma-activities" ninja -C $(BUILD_WORK)/plasma-activities/build install
	$(call AFTER_BUILD,copy)
endif

plasma-activities-package: plasma-activities-stage
	rm -rf $(BUILD_DIST)/plasma-activities $(BUILD_DIST)/plasma-activities-dev
	$(call KF6_COPY_RUNTIME,plasma-activities,plasma-activities)
	$(call KF6_COPY_DEV,plasma-activities,plasma-activities)
	$(call SIGN,plasma-activities,general.xml)
	$(call SIGN,plasma-activities-dev,general.xml)
	$(call PACK,plasma-activities,DEB_PLASMAACTIVITIES_V)
	$(call PACK,plasma-activities-dev,DEB_PLASMAACTIVITIES_V)
	rm -rf $(BUILD_DIST)/plasma-activities $(BUILD_DIST)/plasma-activities-dev

.PHONY: plasma-activities plasma-activities-package
