ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# plasma-wayland-protocols.mk — plasma-wayland-protocols for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Protocol XML + cmake config only; compiled INTO its consumers, so this is
# build-time data (Section: Development, single deb, no SIGN). Pinned to
# kwin 6.1's minimum (1.13.0).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += plasma-wayland-protocols
PLASMAWAYLANDPROTOCOLS_VERSION = $(PWP_VERSION)
DEB_PLASMAWAYLANDPROTOCOLS_V ?= $(PLASMAWAYLANDPROTOCOLS_VERSION)

plasma-wayland-protocols-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-$(PWP_VERSION).tar.xz)
	$(call EXTRACT_TAR,plasma-wayland-protocols-$(PWP_VERSION).tar.xz,plasma-wayland-protocols-$(PWP_VERSION),plasma-wayland-protocols)

ifneq ($(wildcard $(BUILD_WORK)/plasma-wayland-protocols/.build_complete),)
plasma-wayland-protocols:
	@echo "Using previously built plasma-wayland-protocols."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
plasma-wayland-protocols: plasma-wayland-protocols-setup
	mkdir -p $(BUILD_WORK)/plasma-wayland-protocols/build
	cd $(BUILD_WORK)/plasma-wayland-protocols/build && cmake .. \
		-G Ninja \
		$(DEFAULT_CMAKE_FLAGS) \
		-DBUILD_TESTING=OFF
	+ninja -C $(BUILD_WORK)/plasma-wayland-protocols/build
	+DESTDIR="$(BUILD_STAGE)/plasma-wayland-protocols" ninja -C $(BUILD_WORK)/plasma-wayland-protocols/build install
	$(call AFTER_BUILD,copy)
endif

plasma-wayland-protocols-package: plasma-wayland-protocols-stage
	rm -rf $(BUILD_DIST)/plasma-wayland-protocols
	$(call KF6_COPY_ALL,plasma-wayland-protocols,plasma-wayland-protocols)
	$(call PACK,plasma-wayland-protocols,DEB_PLASMAWAYLANDPROTOCOLS_V)
	rm -rf $(BUILD_DIST)/plasma-wayland-protocols

.PHONY: plasma-wayland-protocols plasma-wayland-protocols-package
