ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# plasma-activities.mk — plasma-activities for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Slim in Plasma 6 (Qt Core+DBus only; the old boost dependency is gone -
# audited). libplasma REQUIREs it; the kactivitymanagerd daemon is NOT in this
# subset, activity state just stays static until the workspace layer.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += plasma-activities
PLASMAACTIVITIES_VERSION = $(PLASMA_VERSION)
DEB_PLASMAACTIVITIES_V ?= $(PLASMAACTIVITIES_VERSION)

plasma-activities-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call PLASMA_URL,plasma-activities))
	$(call EXTRACT_TAR,plasma-activities-$(PLASMA_VERSION).tar.xz,plasma-activities-$(PLASMA_VERSION),plasma-activities)
	$(call QT6_WRITE_IOSEXEC_FIXUP)

ifneq ($(wildcard $(BUILD_WORK)/plasma-activities/.build_complete),)
plasma-activities:
	@echo "Using previously built plasma-activities."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
plasma-activities: plasma-activities-setup
	mkdir -p $(BUILD_WORK)/plasma-activities/build
	cd $(BUILD_WORK)/plasma-activities/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/plasma-activities/build
	+DESTDIR="$(BUILD_STAGE)/plasma-activities" ninja -C $(BUILD_WORK)/plasma-activities/build install
	$(call AFTER_BUILD,copy)
endif

plasma-activities-package: plasma-activities-stage
	rm -rf $(BUILD_DIST)/plasma-activities $(BUILD_DIST)/plasma-activities-dev
	$(call KF6_COPY_RUNTIME,plasma-activities,plasma-activities)
	$(call KF6_COPY_DEV,plasma-activities,plasma-activities)
	$(call SIGN,plasma-activities,general.xml)
	$(call SIGN,plasma-activities-dev,general.xml)
	$(call PACK,plasma-activities,DEB_PLASMAACTIVITIES_V)
	$(call PACK,plasma-activities-dev,DEB_PLASMAACTIVITIES_V)
	rm -rf $(BUILD_DIST)/plasma-activities $(BUILD_DIST)/plasma-activities-dev

.PHONY: plasma-activities plasma-activities-package
