ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# solid.mk — kf6-solid for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Backend list pre-patched down to fakehw-only in -setup: the elseif(APPLE)
# branch wants the IOKit backend, which is written against macOS IOKit +
# DiskArbitration (headers/framework absent on the iPhoneOS SDK). Verified
# against v6.3.0: managerbase.cpp gates every backend on the generated
# BUILD_DEVICE_BACKEND_* defines (no Q_OS ifdefs), so a fakehw-only build
# compiles clean and yields an empty device list at runtime unless
# SOLID_FAKEHW points at an XML fixture. KIO only needs the lib to link.
# The emptied elseif(APPLE) block is valid CMake.
# bison/flex on the build host (predicate parser).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += solid
SOLID_VERSION = $(KF6_VERSION)
DEB_SOLID_V ?= $(SOLID_VERSION)

solid-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,solid))
	$(call EXTRACT_TAR,solid-$(KF6_VERSION).tar.xz,solid-$(KF6_VERSION),solid)
	sed -i '/find_package(IOKit REQUIRED)/d' $(BUILD_WORK)/solid/CMakeLists.txt
	sed -i '/add_device_backend(iokit)/d' $(BUILD_WORK)/solid/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/solid/.build_complete),)
solid:
	@echo "Using previously built solid."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
solid: solid-setup
	mkdir -p $(BUILD_WORK)/solid/build
	cd $(BUILD_WORK)/solid/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/solid/build
	+DESTDIR="$(BUILD_STAGE)/solid" ninja -C $(BUILD_WORK)/solid/build install
	$(call AFTER_BUILD,copy)
endif

solid-package: solid-stage
	rm -rf $(BUILD_DIST)/kf6-solid $(BUILD_DIST)/kf6-solid-dev
	$(call KF6_COPY_RUNTIME,solid,kf6-solid)
	$(call KF6_COPY_DEV,solid,kf6-solid)
	$(call SIGN,kf6-solid,general.xml)
	$(call SIGN,kf6-solid-dev,general.xml)
	$(call PACK,kf6-solid,DEB_SOLID_V)
	$(call PACK,kf6-solid-dev,DEB_SOLID_V)
	rm -rf $(BUILD_DIST)/kf6-solid $(BUILD_DIST)/kf6-solid-dev

.PHONY: solid solid-package
