ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# solid.mk — kf6-solid for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# Re-audited 2026-07-08: the elseif(APPLE) branch no longer goes fakehw-only.
# It previously wanted the IOKit + DiskArbitration backend (headers/framework
# absent on the iPhoneOS SDK), which is genuinely unbuildable, but Solid 6.3.0
# also ships a plain-QtDBus upower backend (device/backends/upower: pure
# org.freedesktop.UPower client, no udev/sysfs, no Q_OS ifdefs anywhere in
# managerbase.cpp's BUILD_DEVICE_BACKEND_* gating) that the generic
# 'elseif (NOT ANDROID)' Unix branch already uses. xios-fhs's xios-hwbridged
# daemon owns org.freedesktop.UPower on-device (backed by real IOKit power
# sources), so recipes/solid-ios-fixes.sh swaps elseif(APPLE) to the upower
# backend instead of iokit. That backend needs Qt6::DBus, whose own
# find_package is separately APPLE-guarded off ('Windows & Mac have backends
# that don't use DBus' - true for macOS's IOKit backend, no longer true once
# APPLE means iOS-on-upower), so the fixes script widens that guard too. No new
# Depends: qt6-base already ships Qt6::DBus and Depends: dbus (kdbusaddons/
# kglobalaccel precedent). Runtime-only relationship to xios-fhs (Provides:
# xios-hwbridge): with no UPower bus owner the backend just enumerates zero
# devices, the same graceful empty-list behavior fakehw had, so it is not
# wired as a hard package Depends. KIO only needs the lib to link either way.
# bison/flex on the build host (predicate parser).
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += solid
SOLID_VERSION = $(KF6_VERSION)
DEB_SOLID_V ?= $(SOLID_VERSION)+ios1

solid-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,solid))
	$(call EXTRACT_TAR,solid-$(KF6_VERSION).tar.xz,solid-$(KF6_VERSION),solid)
	bash /work/recipes/solid-ios-fixes.sh $(BUILD_WORK)/solid
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/solid/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/solid/.build_complete),)
solid:
	@echo "Using previously built solid."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
solid: solid-setup
	mkdir -p $(BUILD_WORK)/solid/build
	cd $(BUILD_WORK)/solid/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/solid/build
	+DESTDIR="$(BUILD_STAGE)/solid" ninja -C $(BUILD_WORK)/solid/build install
	$(call AFTER_BUILD,copy)
endif

solid-package: solid-stage
	rm -rf $(BUILD_DIST)/kf6-solid $(BUILD_DIST)/kf6-solid-dev
	$(call KF6_COPY_RUNTIME,solid,kf6-solid)
	$(call KF6_COPY_DEV,solid,kf6-solid)
	$(call SIGN,kf6-solid,general.xml)
	$(call SIGN,kf6-solid-dev,general.xml)
	$(call PACK,kf6-solid,DEB_SOLID_V)
	$(call PACK,kf6-solid-dev,DEB_SOLID_V)
	rm -rf $(BUILD_DIST)/kf6-solid $(BUILD_DIST)/kf6-solid-dev

.PHONY: solid solid-package
