ifneq ($(PROCURSUS),1)
$(error Use the main Makefile)
endif

# sonnet.mk — kf6-sonnet for rootless iOS (KDE flavor, layer K; docs/kde-plasma-plan.md).
# No backends staged (no hunspell/aspell debs), which sonnet supports: the
# core lib builds with zero plugins and reports no spellcheckers at runtime.
# The APPLE nsspellchecker plugin is also removed: it is macOS AppKit code
# (#import <AppKit/AppKit.h>), unavailable in the iPhoneOS SDK.
# Only in the subset because KTextWidgets (via KXmlGui, via KCMUtils) links it.
# Generated by tools/gen-kf6-recipes.py from the K0 audit table; regenerating
# overwrites hand edits (fold phase-2 fixes back into the table).

SUBPROJECTS += sonnet
SONNET_VERSION = $(KF6_VERSION)
DEB_SONNET_V ?= $(SONNET_VERSION)

sonnet-setup: setup
	$(call DOWNLOAD_FILES,$(BUILD_SOURCE),$(call KF6_URL,sonnet))
	$(call EXTRACT_TAR,sonnet-$(KF6_VERSION).tar.xz,sonnet-$(KF6_VERSION),sonnet)
	sed -i '/add_subdirectory([[:space:]]*nsspellchecker[[:space:]]*)/d' $(BUILD_WORK)/sonnet/src/plugins/CMakeLists.txt
	sed -i '/^[[:space:]]*ecm_install_po_files_as_qm(/s/^/# ios-bringup-no-linguist: /' $(BUILD_WORK)/sonnet/CMakeLists.txt
	$(call QT6_WRITE_IOSEXEC_FIXUP)
	$(call QT6_RM_SHADOW_HEADERS)

ifneq ($(wildcard $(BUILD_WORK)/sonnet/.build_complete),)
sonnet:
	@echo "Using previously built sonnet."
else
# Deps come pre-staged from build_base (mutter.mk precedent, no make-level
# prereqs); build-kf6.sh runs the targets in audit wave order.
sonnet: sonnet-setup
	mkdir -p $(BUILD_WORK)/sonnet/build
	cd $(BUILD_WORK)/sonnet/build && cmake .. \
		-G Ninja \
		$(KF6_CMAKE_FLAGS)
	+ninja -C $(BUILD_WORK)/sonnet/build
	+DESTDIR="$(BUILD_STAGE)/sonnet" ninja -C $(BUILD_WORK)/sonnet/build install
	$(call AFTER_BUILD,copy)
endif

sonnet-package: sonnet-stage
	rm -rf $(BUILD_DIST)/kf6-sonnet $(BUILD_DIST)/kf6-sonnet-dev
	$(call KF6_COPY_RUNTIME,sonnet,kf6-sonnet)
	$(call KF6_COPY_DEV,sonnet,kf6-sonnet)
	$(call SIGN,kf6-sonnet,general.xml)
	$(call SIGN,kf6-sonnet-dev,general.xml)
	$(call PACK,kf6-sonnet,DEB_SONNET_V)
	$(call PACK,kf6-sonnet-dev,DEB_SONNET_V)
	rm -rf $(BUILD_DIST)/kf6-sonnet $(BUILD_DIST)/kf6-sonnet-dev

.PHONY: sonnet sonnet-package
