#!/bin/sh
# install-gnome-boot.sh — install the gnome-shell boot set on the iPad in dependency order.
# GENERATED by the gnome-session agent from out/ deb metadata (dependency closure of
# gnome-shell + gnome-session + gsd + the stubs + the gi:// boot-blocker client libs).
# Run on-device from the dir holding the debs (scp x11/linux-build/out/*.deb first), e.g:
#   scp x11/linux-build/out/*.deb root@ipad:/var/jb/tmp/boot/ && ssh root@ipad 'cd /var/jb/tmp/boot && sh install-gnome-boot.sh'
# dpkg -i in this exact order avoids apt's dep-resolver touching the already-broken tree
# (see the libwayland-server0 note). apt-get -f install is DELIBERATELY not called — on this
# device --fix-broken can REMOVE libmutter. Verify with 'apt-get check' after.
set -e
DEBS="\
  hicolor-icon-theme_0.17_iphoneos-arm64.deb \
  adwaita-icon-theme_46.0_iphoneos-arm64.deb \
  angle_2.1.0+git20260630.a32d31d_iphoneos-arm64.deb \
  dbus_1.14.10_iphoneos-arm64.deb \
  libglib2.0-0_2.78.0_iphoneos-arm64.deb \
  dconf_0.40.0_iphoneos-arm64.deb \
  libgirepository-1.0-1_1.78.0_iphoneos-arm64.deb \
  gir1.2-freedesktop_1.78.0_iphoneos-arm64.deb \
  gir1.2-glib-2.0_1.78.0_iphoneos-arm64.deb \
  libgtkintl_1.0_iphoneos-arm64.deb \
  libmozjs-115-0_115.12.0_iphoneos-arm64.deb \
  libfontconfig1_2.14.0_iphoneos-arm64.deb \
  libpixman-1-0_0.42.2_iphoneos-arm64.deb \
  libxcb-render0_1.14_iphoneos-arm64.deb \
  libcairo2_1.16.0-3_iphoneos-arm64.deb \
  libcairo-gobject2_1.16.0-3_iphoneos-arm64.deb \
  libgjs0_1.78.0_iphoneos-arm64.deb \
  gjs_1.78.0_iphoneos-arm64.deb \
  libglib2.0-bin_2.78.0_iphoneos-arm64.deb \
  libgdk-pixbuf-2.0-0_2.42.12_iphoneos-arm64.deb \
  libgraphite2-3_1.3.14_iphoneos-arm64.deb \
  libharfbuzz0b_2.8.1_iphoneos-arm64.deb \
  libfribidi0_1.0.13_iphoneos-arm64.deb \
  libpango-1.0-0_1.50.14_iphoneos-arm64.deb \
  libatk1.0-0_2.38.0_iphoneos-arm64.deb \
  libepoxy0_1.5.7_iphoneos-arm64.deb \
  libxfixes3_6.0.1_iphoneos-arm64.deb \
  libxcursor1_1.2.0_iphoneos-arm64.deb \
  libxinerama1_1.1.4_iphoneos-arm64.deb \
  libgtk-3-0_3.24.38_iphoneos-arm64.deb \
  libgraphene-1.0-0_1.10.8_iphoneos-arm64.deb \
  libxml2_2.9.12_iphoneos-arm64.deb \
  libxkbcommon0_1.7.0_iphoneos-arm64.deb \
  libepoll-shim0_0.0.20240608_iphoneos-arm64.deb \
  libwayland0_1.23.1_iphoneos-arm64.deb \
  libcairo-script-interpreter2_1.16.0-3_iphoneos-arm64.deb \
  libgtk-4-1_4.14.5_iphoneos-arm64.deb \
  gsettings-desktop-schemas_46.1_iphoneos-arm64.deb \
  iso-codes_4.15.0_iphoneos-arm64.deb \
  libgnome-desktop-4-2_44.1_iphoneos-arm64.deb \
  libjson-glib-1.0-0_1.8.0_iphoneos-arm64.deb \
  gnome-session_46.0_iphoneos-arm64.deb \
  libnotify4_0.8.3_iphoneos-arm64.deb \
  libpolkit-gobject-1-0_124_iphoneos-arm64.deb \
  libpulse0_17.0_iphoneos-arm64.deb \
  gnome-settings-daemon_46.0_iphoneos-arm64.deb \
  liblcms2-2_2.12_iphoneos-arm64.deb \
  libcolord2_1.4.7_iphoneos-arm64.deb \
  libei1_1.2.1_iphoneos-arm64.deb \
  libmutter-14-0_46.0_iphoneos-arm64.deb \
  libatspi2.0-0_2.52.0_iphoneos-arm64.deb \
  libatk-bridge2.0-0_2.52.0_iphoneos-arm64.deb \
  libgcr-4-4_4.2.1_iphoneos-arm64.deb \
  libpolkit-agent-1-0_124_iphoneos-arm64.deb \
  libibus-1.0-5_1.5.29_iphoneos-arm64.deb \
  libstartup-notification0_0.12_iphoneos-arm64.deb \
  gnome-shell_46.0_iphoneos-arm64.deb \
  libaccountsservice0_23.13.9_iphoneos-arm64.deb \
  libgdm1_46.0_iphoneos-arm64.deb \
  libgeoclue-2-0_2.7.1_iphoneos-arm64.deb \
  libpsl5_0.21.5_iphoneos-arm64.deb \
  libsoup-3.0-0_3.4.4_iphoneos-arm64.deb \
  libgeocode-glib-2-0_3.26.4_iphoneos-arm64.deb \
  libgweather-4-0_4.4.2_iphoneos-arm64.deb \
  libupower-glib3_1.90.2_iphoneos-arm64.deb \
  xios-session-stubs_0.1.2_iphoneos-arm64.deb \
"

# The -dev debs below are needed ONLY for gtk4-gpu's on-device gir/typelib scan
# (headers + pkg-config), not for boot. Install them before running the gir batch.
GIR_DEV_DEBS="\
  libmutter-14-dev_46.0_iphoneos-arm64.deb \
  libgjs-dev_1.78.0_iphoneos-arm64.deb \
  libaccountsservice-dev_23.13.9_iphoneos-arm64.deb \
  libgdm-dev_46.0_iphoneos-arm64.deb \
  libupower-glib-dev_1.90.2_iphoneos-arm64.deb \
  libgeocode-glib-2-dev_3.26.4_iphoneos-arm64.deb \
  libgweather-4-dev_4.4.2_iphoneos-arm64.deb \
  libgeoclue-dev_2.7.1_iphoneos-arm64.deb \
"

echo "==> installing 66 boot debs in dependency order"
dpkg -i $DEBS
echo "==> boot set installed. For the on-device gir scan, also: dpkg -i $GIR_DEV_DEBS"
echo "==> then: apt-get check   (must be clean; do NOT run apt --fix-broken on this device)"
