#!/bin/sh
set -e

PATH="@MEMO_PREFIX@@MEMO_SUB_PREFIX@/bin:@MEMO_PREFIX@@MEMO_SUB_PREFIX@/sbin:@MEMO_PREFIX@@MEMO_SUB_PREFIX@/local/bin:$PATH"
export PATH

ICONDIR="@MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/icons/hicolor"
APPLICATIONDIR="@MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/applications"

if command -v gtk-update-icon-cache >/dev/null 2>&1 && [ -d "$ICONDIR" ]; then
    gtk-update-icon-cache -q -f "$ICONDIR" >/dev/null 2>&1 || true
fi
if command -v update-desktop-database >/dev/null 2>&1 && [ -d "$APPLICATIONDIR" ]; then
    update-desktop-database -q "$APPLICATIONDIR" >/dev/null 2>&1 || true
fi
if command -v xios-launcher-sync >/dev/null 2>&1; then
    xios-launcher-sync --sync --native --only thunar >/dev/null 2>&1 || true
fi

exit 0
