#ifndef PULSE_ERROR_H
#define PULSE_ERROR_H

enum {
    PA_OK = 0,
    PA_ERR_ACCESS,
    PA_ERR_COMMAND,
    PA_ERR_INVALID,
    PA_ERR_EXIST,
    PA_ERR_NOENTITY,
    PA_ERR_CONNECTIONREFUSED,
    PA_ERR_PROTOCOL,
    PA_ERR_TIMEOUT,
    PA_ERR_AUTHKEY,
    PA_ERR_INTERNAL,
    PA_ERR_CONNECTIONTERMINATED,
    PA_ERR_KILLED,
    PA_ERR_INVALIDSERVER,
    PA_ERR_MODINITFAILED,
    PA_ERR_BADSTATE,
    PA_ERR_NODATA,
    PA_ERR_VERSION,
    PA_ERR_TOOLARGE,
    PA_ERR_NOTSUPPORTED,
    PA_ERR_UNKNOWN,
    PA_ERR_NOEXTENSION,
    PA_ERR_OBSOLETE,
    PA_ERR_NOTIMPLEMENTED,
    PA_ERR_FORKED,
    PA_ERR_IO,
    PA_ERR_BUSY,
    PA_ERR_MAX
};

const char *pa_strerror(int error);

#endif

