/* gudevenumtypes.h — normally generated by glib-mkenums. Hand-written for the iOS stub:
 * the only public enum is GUdevDeviceType (gudevenums.h). */
#ifndef __G_UDEV_ENUM_TYPES_H__
#define __G_UDEV_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS

GType g_udev_device_type_get_type (void);
#define G_UDEV_TYPE_DEVICE_TYPE (g_udev_device_type_get_type ())

G_END_DECLS

#endif /* __G_UDEV_ENUM_TYPES_H__ */
